// packages/angular/src/components/input/input.component.ts
/**
 * @author Bùi Trọng Hiếu
 * @email kevinbui210191@gmail.com
 * @desc Text input with label, hints, and error messages
 */

import { Component, Input, Output, EventEmitter, forwardRef, ChangeDetectionStrategy } from '@angular/core';
import { NG_VALUE_ACCESSOR, ControlValueAccessor } from '@angular/forms';
import { CommonModule } from '@angular/common';
import { cn } from '@/lib/utils';

@Component({
  selector: 'ui-input',
  standalone: true,
  imports: [CommonModule],
  template: `
    <input
      [attr.type]="type"
      [value]="value"
      [attr.disabled]="disabled ? '' : null"
      [attr.readonly]="readonly ? '' : null"
      [attr.maxlength]="maxlength ?? null"
      [attr.autocomplete]="autocomplete ?? null"
      [attr.aria-invalid]="ariaInvalidAttr"
      [attr.name]="name ?? null"
      [attr.id]="id ?? null"
      [attr.required]="required ? '' : null"
      [placeholder]="placeholder"
      (input)="onInput($event)"
      (focus)="onFocus()"
      (blur)="onBlur()"
      [class]="inputClasses"
    />
  `,
  providers: [
    {
      provide: NG_VALUE_ACCESSOR,
      useExisting: forwardRef(() => InputComponent),
      multi: true,
    },
  ],
  changeDetection: ChangeDetectionStrategy.Default,
})
export class InputComponent implements ControlValueAccessor {
  @Input() type: string = 'text';
  @Input() placeholder?: string;
  @Input() class?: string;
  @Input() disabled: boolean = false;
  @Input() readonly: boolean = false;
  @Input() maxlength?: number;
  @Input() autocomplete?: string;
  @Input() ariaInvalid?: string | boolean;
  @Input() name?: string;
  @Input() id?: string;
  @Input() required: boolean = false;

  @Output() valueChange = new EventEmitter<string | number>();
  @Output() inputFocus = new EventEmitter<void>();
  @Output() inputBlur = new EventEmitter<void>();

  value: string | number = '';
  onChange: (value: string | number) => void = () => {};
  onTouched: () => void = () => {};

  get inputClasses(): string {
    return cn(
      'flex h-10 w-full rounded-md border border-input bg-background px-3 py-2 text-sm ring-offset-background file:border-0 file:bg-transparent file:text-sm file:font-medium file:text-foreground placeholder:text-muted-foreground focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:cursor-not-allowed disabled:opacity-50',
      this.class
    );
  }

  onInput(event: Event): void {
    const target = event.target as HTMLInputElement;
    this.value = target.value;
    this.onChange(this.value);
    this.valueChange.emit(this.value);
  }

  writeValue(value: string | number | null): void {
    this.value = value || '';
  }

  registerOnChange(fn: (value: string | number) => void): void {
    this.onChange = fn;
  }

  registerOnTouched(fn: () => void): void {
    this.onTouched = fn;
  }

  setDisabledState(isDisabled: boolean): void {
    this.disabled = isDisabled;
  }

  onFocus(): void {
    this.inputFocus.emit();
  }

  onBlur(): void {
    this.onTouched();
    this.inputBlur.emit();
  }

  get ariaInvalidAttr(): string | null {
    if (this.ariaInvalid === undefined || this.ariaInvalid === null) return null;
    return String(this.ariaInvalid);
  }
}

// packages/react-native/src/components/input/Input.tsx
/**
 * @author Bùi Trọng Hiếu
 * @email kevinbui210191@gmail.com
 * @desc Text input component with label, placeholder, and error states
 */

import * as React from 'react';
import { TextInput, TextInputProps, View, Text } from 'react-native';
import { cn } from '@/lib/utils';

export interface InputProps extends TextInputProps {
  /** Controlled value */
  value?: string;
  /** Placeholder text */
  placeholder?: string;
  /** Whether the input is editable */
  editable?: boolean;
  /** Change handler */
  onChangeText?: (text: string) => void;
  /** Blur handler */
  onBlur?: (event: any) => void;
  /** Focus handler */
  onFocus?: (event: any) => void;
  /** CSS class names for the input */
  className?: string;
  /** Label text */
  label?: string;
  /** Error text */
  error?: string;
  /** Wrapper class name */
  containerClassName?: string;
  /** Label class name */
  labelClassName?: string;
  /** Error text class name */
  errorClassName?: string;
}

const Input = React.forwardRef<React.ElementRef<typeof TextInput>, InputProps>(
  ({ className, containerClassName, label, error, labelClassName, errorClassName, ...props }, ref) => {
    return (
      <View className={cn('flex flex-col gap-1.5', containerClassName)}>
        {label && (
          <Text className={cn('text-sm font-medium text-foreground', labelClassName)}>
            {label}
          </Text>
        )}
        <TextInput
          ref={ref}
          className={cn(
            'h-10 rounded-md border border-input bg-background px-3 py-2 text-sm text-foreground placeholder:text-muted-foreground',
            'focus:border-ring focus:ring-2 focus:ring-ring focus:ring-offset-2',
            'disabled:cursor-not-allowed disabled:opacity-50',
            error && 'border-destructive focus:border-destructive focus:ring-destructive',
            className
          )}
          placeholderTextColor="rgb(156 163 175)" // text-muted-foreground
          {...props}
        />
        {error && (
          <Text className={cn('text-sm text-destructive', errorClassName)}>
            {error}
          </Text>
        )}
      </View>
    );
  }
);

Input.displayName = 'Input';

export { Input };
