// examples/angular-example/src/app/layouts/admin-layout/admin-layout.component.ts
import {Component} from '@angular/core';
import {RouterLink, RouterLinkActive, RouterOutlet} from '@angular/router';
import {CommonModule} from '@angular/common';

interface MenuItem {
	name: string;
	path: string;
}

interface MenuSection {
	title: string;
	icon: string;
	items: MenuItem[];
}

@Component({
	selector: 'app-admin-layout',
	standalone: true,
	imports: [CommonModule, RouterOutlet, RouterLink, RouterLinkActive],
	templateUrl: './admin-layout.component.html',
	styleUrls: ['./admin-layout.component.css'],
})
export class AdminLayoutComponent {
	expandedSections: string[] = ['Form Components'];

	menuSections: MenuSection[] = [
		{
			title: 'Form Components',
			icon: 'form-input',
			items: [
				{name: 'Button', path: '/button'},
				{name: 'Input', path: '/input'},
				{name: 'Checkbox', path: '/checkbox'},
				{name: 'Radio Group', path: '/radio-group'},
				{name: 'Select', path: '/select'},
				{name: 'Slider', path: '/slider'},
				{name: 'Switch', path: '/switch'},
				{name: 'Textarea', path: '/textarea'},
				{name: 'Label', path: '/label'},
			],
		},
		{
			title: 'Layout Components',
			icon: 'layout',
			items: [
				{name: 'Separator', path: '/separator'},
				{name: 'Accordion', path: '/accordion'},
				{name: 'Collapsible', path: '/collapsible'},
				{name: 'Tabs', path: '/tabs'},
				{name: 'Scroll Area', path: '/scroll-area'},
				{name: 'Aspect Ratio', path: '/aspect-ratio'},
				{name: 'Resizable', path: '/resizable'},
				{name: 'Sheet', path: '/sheet'},
				{name: 'Toolbar', path: '/toolbar'},
			],
		},
		{
			title: 'Navigation Components',
			icon: 'navigation',
			items: [
				{name: 'Navigation Menu', path: '/navigation-menu'},
				{name: 'Menubar', path: '/menubar'},
				{name: 'Context Menu', path: '/context-menu'},
				{name: 'Dropdown Menu', path: '/dropdown-menu'},
				{name: 'Pagination', path: '/pagination'},
				{name: 'Command', path: '/command'},
			],
		},
		{
			title: 'Overlay Components',
			icon: 'layers',
			items: [
				{name: 'Dialog', path: '/dialog'},
				{name: 'Alert Dialog', path: '/alert-dialog'},
				{name: 'Popover', path: '/popover'},
				{name: 'Tooltip', path: '/tooltip'},
				{name: 'Hover Card', path: '/hover-card'},
			],
		},
		{
			title: 'Data Display Components',
			icon: 'database',
			items: [
				{name: 'Avatar', path: '/avatar'},
				{name: 'Progress', path: '/progress'},
				{name: 'Table', path: '/table'},
				{name: 'Empty', path: '/empty'},
				{name: 'Skeleton', path: '/skeleton'},
				{name: 'Kbd', path: '/kbd'},
				{name: 'Typography', path: '/typography'},
			],
		},
		{
			title: 'Date & Time',
			icon: 'calendar',
			items: [
				{name: 'Calendar', path: '/calendar'},
				{name: 'Calendar Range', path: '/calendar-range'},
			],
		},
		{
			title: 'Interactive Components',
			icon: 'toggle',
			items: [
				{name: 'Toggle', path: '/toggle'},
				{name: 'Toggle Group', path: '/toggle-group'},
			],
		},
		{
			title: 'Advanced Components',
			icon: 'command',
			items: [
				{name: 'Command', path: '/command'},
				{name: 'Sheet', path: '/sheet'},
				{name: 'Toolbar', path: '/toolbar'},
				{name: 'Tags Input', path: '/tags-input'},
			],
		},
	];

	toggleSection(title: string): void {
		const index = this.expandedSections.indexOf(title);
		if (index === -1) {
			this.expandedSections.push(title);
		} else {
			this.expandedSections.splice(index, 1);
		}
	}

	isExpanded(title: string): boolean {
		return this.expandedSections.includes(title);
	}
}

<div class="flex h-screen bg-background">
	<!-- Sidebar -->
	<aside class="w-64 border-r bg-card shadow-sm">
		<div class="flex h-16 items-center gap-2 border-b px-6 bg-background/50">
			<svg
				class="h-6 w-6 text-primary"
				xmlns="http://www.w3.org/2000/svg"
				viewBox="0 0 24 24"
				fill="none"
				stroke="currentColor"
				stroke-width="2"
				stroke-linecap="round"
				stroke-linejoin="round"
			>
				<rect width="7" height="9" x="3" y="3" rx="1" />
				<rect width="7" height="5" x="14" y="3" rx="1" />
				<rect width="7" height="9" x="14" y="12" rx="1" />
				<rect width="7" height="5" x="3" y="16" rx="1" />
			</svg>
			<h1 class="text-xl font-bold tracking-tight">Galaxy UI</h1>
		</div>

		<div class="h-[calc(100vh-4rem)] overflow-y-auto">
			<div class="p-3 space-y-1">
				<div *ngFor="let section of menuSections">
					<button
						class="w-full flex items-center justify-between px-3 py-2 text-sm font-medium rounded-md hover:bg-accent transition-colors"
						(click)="toggleSection(section.title)"
					>
						<span class="flex items-center gap-2">
							<svg
								class="h-4 w-4"
								xmlns="http://www.w3.org/2000/svg"
								viewBox="0 0 24 24"
								fill="none"
								stroke="currentColor"
								stroke-width="2"
								stroke-linecap="round"
								stroke-linejoin="round"
							>
								<rect width="7" height="7" x="3" y="3" rx="1" />
								<rect width="7" height="7" x="14" y="3" rx="1" />
								<rect width="7" height="7" x="14" y="14" rx="1" />
								<rect width="7" height="7" x="3" y="14" rx="1" />
							</svg>
							<span>{{ section.title }}</span>
						</span>
						<svg
							*ngIf="isExpanded(section.title)"
							class="h-4 w-4"
							xmlns="http://www.w3.org/2000/svg"
							viewBox="0 0 24 24"
							fill="none"
							stroke="currentColor"
							stroke-width="2"
							stroke-linecap="round"
							stroke-linejoin="round"
						>
							<path d="m6 9 6 6 6-6" />
						</svg>
						<svg
							*ngIf="!isExpanded(section.title)"
							class="h-4 w-4"
							xmlns="http://www.w3.org/2000/svg"
							viewBox="0 0 24 24"
							fill="none"
							stroke="currentColor"
							stroke-width="2"
							stroke-linecap="round"
							stroke-linejoin="round"
						>
							<path d="m9 18 6-6-6-6" />
						</svg>
					</button>

					<div *ngIf="isExpanded(section.title)" class="ml-6 mt-1 space-y-0.5 mb-2">
						<a
							*ngFor="let item of section.items"
							[routerLink]="item.path"
							routerLinkActive="bg-accent text-accent-foreground font-medium"
							class="block px-3 py-2 text-sm rounded-md hover:bg-accent transition-colors"
						>
							{{ item.name }}
						</a>
					</div>
				</div>
			</div>
		</div>
	</aside>

	<!-- Main Content -->
	<main class="flex-1 overflow-auto bg-background p-8">
		<router-outlet />
	</main>
</div>

// examples/vue-example/src/layouts/AdminLayout.vue
<script setup lang="ts">
import {ref} from 'vue'
import {useRoute} from 'vue-router'
import {Button} from '@/components/ui/button'
import {
	ChevronDown,
	ChevronRight,
	LayoutDashboard,
	FormInput,
	Layout,
	Navigation,
	Layers,
	Database,
	Type,
	Calendar,
	Command,
} from 'lucide-vue-next'
import {cn} from '@/lib/utils'

interface MenuItem {
	name: string
	path: string
}

interface MenuSection {
	title: string
	icon: any
	items: MenuItem[]
}

const route = useRoute()
const expandedSections = ref<string[]>(['Form Components'])

const menuSections: MenuSection[] = [
	{
		title: 'Form Components',
		icon: FormInput,
		items: [
			{name: 'Button', path: '/button'},
			{name: 'Input', path: '/input'},
			{name: 'Checkbox', path: '/checkbox'},
			{name: 'Radio Group', path: '/radio-group'},
			{name: 'Select', path: '/select'},
			{name: 'Slider', path: '/slider'},
			{name: 'Switch', path: '/switch'},
			{name: 'Textarea', path: '/textarea'},
			{name: 'Label', path: '/label'},
		],
	},
	{
		title: 'Layout Components',
		icon: Layout,
		items: [
			{name: 'Separator', path: '/separator'},
			{name: 'Accordion', path: '/accordion'},
			{name: 'Collapsible', path: '/collapsible'},
			{name: 'Tabs', path: '/tabs'},
		],
	},
	{
		title: 'Navigation Components',
		icon: Navigation,
		items: [
			{name: 'Navigation Menu', path: '/navigation-menu'},
			{name: 'Menubar', path: '/menubar'},
			{name: 'Context Menu', path: '/context-menu'},
			{name: 'Dropdown Menu', path: '/dropdown-menu'},
		],
	},
	{
		title: 'Overlay Components',
		icon: Layers,
		items: [
			{name: 'Dialog', path: '/dialog'},
			{name: 'Alert Dialog', path: '/alert-dialog'},
			{name: 'Popover', path: '/popover'},
			{name: 'Tooltip', path: '/tooltip'},
			{name: 'Hover Card', path: '/hover-card'},
		],
	},
	{
		title: 'Data Display Components',
		icon: Database,
		items: [
			{name: 'Avatar', path: '/avatar'},
			{name: 'Progress', path: '/progress'},
			{name: 'Table', path: '/table'},
			{name: 'Pagination', path: '/pagination'},
			{name: 'Empty', path: '/empty'},
			{name: 'Skeleton', path: '/skeleton'},
		],
	},
	{
		title: 'Typography & Utilities',
		icon: Type,
		items: [
			{name: 'Typography', path: '/typography'},
			{name: 'Kbd', path: '/kbd'},
		],
	},
	{
		title: 'Date & Time',
		icon: Calendar,
		items: [
			{name: 'Calendar', path: '/calendar'},
			{name: 'Calendar Range', path: '/calendar-range'},
		],
	},
	{
		title: 'Advanced Components',
		icon: Command,
		items: [
			{name: 'Command', path: '/command'},
			{name: 'Sheet', path: '/sheet'},
			{name: 'Toolbar', path: '/toolbar'},
			{name: 'Tags Input', path: '/tags-input'},
		],
	},
]

const toggleSection = (title: string) => {
	const index = expandedSections.value.indexOf(title)
	if (index === -1) {
		expandedSections.value.push(title)
	} else {
		expandedSections.value.splice(index, 1)
	}
}

const isExpanded = (title: string) => expandedSections.value.includes(title)
const isActive = (path: string) => route.path === path
</script>

<template>
	<div class="flex h-screen bg-background">
		<!-- Sidebar -->
		<aside class="w-64 border-r bg-card shadow-sm">
			<div class="flex h-16 items-center gap-2 border-b px-6 bg-background/50">
				<LayoutDashboard class="h-6 w-6 text-primary" />
				<h1 class="text-xl font-bold tracking-tight">Galaxy UI</h1>
			</div>

			<div class="h-[calc(100vh-4rem)] overflow-y-auto">
				<div class="p-3 space-y-1">
					<div v-for="section in menuSections" :key="section.title">
						<Button
							variant="ghost"
							class="w-full justify-between hover:bg-accent text-sm"
							@click="toggleSection(section.title)"
						>
							<span class="flex items-center gap-2 font-medium">
								<component :is="section.icon" class="h-4 w-4" />
								<span>{{ section.title }}</span>
							</span>
							<ChevronDown v-if="isExpanded(section.title)" class="h-4 w-4" />
							<ChevronRight v-else class="h-4 w-4" />
						</Button>

						<div v-if="isExpanded(section.title)" class="ml-6 mt-1 space-y-0.5 mb-2">
							<router-link
								v-for="item in section.items"
								:key="item.path"
								:to="item.path"
							>
								<Button
									variant="ghost"
									size="sm"
									:class="
										cn(
											'w-full justify-start text-sm font-normal',
											isActive(item.path) &&
												'bg-accent text-accent-foreground font-medium'
										)
									"
								>
									{{ item.name }}
								</Button>
							</router-link>
						</div>
					</div>
				</div>
			</div>
		</aside>

		<!-- Main Content -->
		<main class="flex-1 overflow-auto bg-background p-8">
			<router-view />
		</main>
	</div>
</template>
