// packages/angular/src/components/typography/typography.component.ts
/**
 * @author Bùi Trọng Hiếu
 * @email kevinbui210191@gmail.com
 * @desc Typography component with 11 text style variants
 */

import { Component, Input } from '@angular/core'
import { CommonModule } from '@angular/common'
import { cn } from '@/lib/utils'

type TypographyVariant = 'h1' | 'h2' | 'h3' | 'h4' | 'p' | 'blockquote' | 'code' | 'lead' | 'large' | 'small' | 'muted'

const variantStyles: Record<TypographyVariant, string> = {
  h1: 'scroll-m-20 text-4xl font-extrabold tracking-tight lg:text-5xl',
  h2: 'scroll-m-20 border-b pb-2 text-3xl font-semibold tracking-tight first:mt-0',
  h3: 'scroll-m-20 text-2xl font-semibold tracking-tight',
  h4: 'scroll-m-20 text-xl font-semibold tracking-tight',
  p: 'leading-7 [&:not(:first-child)]:mt-6',
  blockquote: 'mt-6 border-l-2 pl-6 italic',
  code: 'relative rounded bg-muted px-[0.3rem] py-[0.2rem] font-mono text-sm font-semibold',
  lead: 'text-xl text-muted-foreground',
  large: 'text-lg font-semibold',
  small: 'text-sm font-medium leading-none',
  muted: 'text-sm text-muted-foreground',
}

@Component({
  selector: 'ui-typography',
  standalone: true,
  imports: [CommonModule],
  template: `
    <h1 *ngIf="variant === 'h1'" [class]="className"><ng-content /></h1>
    <h2 *ngIf="variant === 'h2'" [class]="className"><ng-content /></h2>
    <h3 *ngIf="variant === 'h3'" [class]="className"><ng-content /></h3>
    <h4 *ngIf="variant === 'h4'" [class]="className"><ng-content /></h4>
    <p *ngIf="variant === 'p' || variant === 'lead' || variant === 'muted'" [class]="className"><ng-content /></p>
    <blockquote *ngIf="variant === 'blockquote'" [class]="className"><ng-content /></blockquote>
    <code *ngIf="variant === 'code'" [class]="className"><ng-content /></code>
    <div *ngIf="variant === 'large'" [class]="className"><ng-content /></div>
    <small *ngIf="variant === 'small'" [class]="className"><ng-content /></small>
  `,
})
export class TypographyComponent {
  /**
   * CSS class
   */
  @Input() class?: string

  /**
   * Typography variant
   * @default "p"
   */
  @Input() variant: TypographyVariant = 'p'

  get className() {
    return cn(variantStyles[this.variant], this.class)
  }
}

// examples/rn-expo-admin/components/ui/typography/Typography.tsx
import * as React from 'react';
import { Text, TextProps, View } from 'react-native';
import { cn } from '@/lib/utils';

export type TypographyVariant =
  | 'h1'
  | 'h2'
  | 'h3'
  | 'h4'
  | 'p'
  | 'lead'
  | 'large'
  | 'small'
  | 'muted'
  | 'blockquote'
  | 'code';

export type TypographyWeight = 'normal' | 'medium' | 'semiBold' | 'bold';

export interface TypographyProps extends Omit<TextProps, 'children'> {
  children: string;
  variant?: TypographyVariant;
  weight?: TypographyWeight;
  color?: string;
  className?: string;
}

export const Typography = React.forwardRef<Text, TypographyProps>(
  (
    {
      children,
      variant = 'p',
      weight,
      color,
      className,
      ...props
    },
    ref
  ) => {
    // Get variant classes
    const variantClasses = getVariantClasses(variant);

    // Get weight classes
    const weightClasses = weight ? getWeightClasses(weight) : '';

    // Special rendering for blockquote and code
    if (variant === 'blockquote') {
      return (
        <View className="pl-4 py-2 border-l-4 border-primary">
          <Text
            ref={ref}
            className={cn(
              variantClasses,
              weightClasses,
              color && `text-[${color}]`,
              className
            )}
            {...props}
          >
            {children}
          </Text>
        </View>
      );
    }

    if (variant === 'code') {
      return (
        <View className="px-2 py-1 bg-muted rounded">
          <Text
            ref={ref}
            className={cn(
              variantClasses,
              weightClasses,
              color && `text-[${color}]`,
              'font-mono',
              className
            )}
            {...props}
          >
            {children}
          </Text>
        </View>
      );
    }

    return (
      <Text
        ref={ref}
        className={cn(
          variantClasses,
          weightClasses,
          color && `text-[${color}]`,
          className
        )}
        {...props}
      >
        {children}
      </Text>
    );
  }
);

Typography.displayName = 'Typography';

// Helper function to get variant classes
function getVariantClasses(variant: TypographyVariant): string {
  switch (variant) {
    case 'h1':
      return 'text-4xl font-extrabold tracking-tight text-foreground';
    case 'h2':
      return 'text-3xl font-semibold tracking-tight text-foreground';
    case 'h3':
      return 'text-2xl font-semibold tracking-tight text-foreground';
    case 'h4':
      return 'text-xl font-semibold tracking-tight text-foreground';
    case 'p':
      return 'text-base leading-7 text-foreground';
    case 'lead':
      return 'text-xl text-muted-foreground';
    case 'large':
      return 'text-lg font-semibold text-foreground';
    case 'small':
      return 'text-sm font-medium leading-none text-foreground';
    case 'muted':
      return 'text-sm text-muted-foreground';
    case 'blockquote':
      return 'text-base italic text-muted-foreground';
    case 'code':
      return 'text-sm bg-muted text-foreground';
    default:
      return 'text-base text-foreground';
  }
}

// Helper function to get weight classes
function getWeightClasses(weight: TypographyWeight): string {
  switch (weight) {
    case 'normal':
      return 'font-normal';
    case 'medium':
      return 'font-medium';
    case 'semiBold':
      return 'font-semibold';
    case 'bold':
      return 'font-bold';
    default:
      return '';
  }
}

// Static methods for each variant
Typography.h1 = (props: Omit<TypographyProps, 'variant'>) => (
  <Typography {...props} variant="h1" />
);

Typography.h2 = (props: Omit<TypographyProps, 'variant'>) => (
  <Typography {...props} variant="h2" />
);

Typography.h3 = (props: Omit<TypographyProps, 'variant'>) => (
  <Typography {...props} variant="h3" />
);

Typography.h4 = (props: Omit<TypographyProps, 'variant'>) => (
  <Typography {...props} variant="h4" />
);

Typography.p = (props: Omit<TypographyProps, 'variant'>) => (
  <Typography {...props} variant="p" />
);

Typography.lead = (props: Omit<TypographyProps, 'variant'>) => (
  <Typography {...props} variant="lead" />
);

Typography.large = (props: Omit<TypographyProps, 'variant'>) => (
  <Typography {...props} variant="large" />
);

Typography.small = (props: Omit<TypographyProps, 'variant'>) => (
  <Typography {...props} variant="small" />
);

Typography.muted = (props: Omit<TypographyProps, 'variant'>) => (
  <Typography {...props} variant="muted" />
);

Typography.blockquote = (props: Omit<TypographyProps, 'variant'>) => (
  <Typography {...props} variant="blockquote" />
);

Typography.code = (props: Omit<TypographyProps, 'variant'>) => (
  <Typography {...props} variant="code" />
);

export type { TypographyProps as TypographyComponentProps };
