// packages/react/src/components/checkbox/Checkbox.tsx
/**
 * @author Bùi Trọng Hiếu
 * @email kevinbui210191@gmail.com
 * @desc Checkbox component - A control that allows the user to toggle between checked and not checked
 */

import * as React from 'react'
import * as CheckboxPrimitive from '@radix-ui/react-checkbox'
import { Check } from 'lucide-react'
import { cn } from '@/lib/utils'

/**
 * Checkbox Props interface
 * @extends React.ComponentPropsWithoutRef<typeof CheckboxPrimitive.Root> - All standard checkbox root attributes
 */
export type CheckboxProps = React.ComponentPropsWithoutRef<
  typeof CheckboxPrimitive.Root
> & {
  /**
   * Checked state (controlled)
   */
  checked?: boolean | 'indeterminate'
  /**
   * Uncontrolled initial checked state
   */
  defaultChecked?: boolean | 'indeterminate'
  /**
   * Called when the checked state changes
   */
  onCheckedChange?: (checked: boolean | 'indeterminate') => void
  /**
   * Disables the checkbox
   * @default false
   */
  disabled?: boolean
  /**
   * Requires a value before form submission
   */
  required?: boolean
  /**
   * Name for form submission
   */
  name?: string
  /**
   * Value for form submission
   * @default 'on'
   */
  value?: string
  /**
   * CSS class names for the checkbox
   */
  className?: string
}

/**
 * Checkbox Component
 * 
 * A control that allows the user to toggle between checked and not checked state.
 * Built on top of Radix UI Checkbox primitive.
 * 
 * @param {CheckboxProps} props - Checkbox component props
 * @param {string} [props.className] - CSS class names for the checkbox
 * @param {boolean|'indeterminate'} [props.checked] - Checked state (controlled)
 * @param {boolean|'indeterminate'} [props.defaultChecked] - Uncontrolled initial checked state
 * @param {(checked: boolean | 'indeterminate') => void} [props.onCheckedChange] - Checked state change handler
 * @param {boolean} [props.disabled=false] - Disables the checkbox
 * @param {boolean} [props.required] - Requires a value before form submission
 * @param {string} [props.name] - Name for form submission
 * @param {string} [props.value='on'] - Value for form submission
 * @param {React.RefObject<React.ElementRef<typeof CheckboxPrimitive.Root>>} ref - Reference to the checkbox element
 * @returns {JSX.Element} Checkbox element
 */
const Checkbox = React.forwardRef<
  React.ElementRef<typeof CheckboxPrimitive.Root>,
  CheckboxProps
>(({ className, ...props }, ref) => (
  <CheckboxPrimitive.Root
    ref={ref}
    className={cn(
      'peer h-4 w-4 shrink-0 rounded-sm border border-primary ring-offset-background focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:cursor-not-allowed disabled:opacity-50 data-[state=checked]:bg-primary data-[state=checked]:text-primary-foreground',
      className
    )}
    {...props}
  >
    <CheckboxPrimitive.Indicator
      className={cn('flex items-center justify-center text-current')}
    >
      <Check className="h-4 w-4" />
    </CheckboxPrimitive.Indicator>
  </CheckboxPrimitive.Root>
))
Checkbox.displayName = CheckboxPrimitive.Root.displayName

export { Checkbox }

// packages/vue/src/components/checkbox/Checkbox.vue
<!--
 * @author Bùi Trọng Hiếu
 * @email kevinbui210191@gmail.com
 * @desc Checkbox component - Accessible checkbox with Radix Vue primitive
-->
<script setup lang="ts">
import { type HTMLAttributes } from 'vue'
import { CheckboxIndicator, CheckboxRoot, type CheckboxRootEmits, type CheckboxRootProps } from 'radix-vue'
import { Check } from 'lucide-vue-next'
import { cn } from '@/lib/utils'

/**
 * Checkbox Props
 * @prop checked - Controlled checked state
 * @prop defaultChecked - Default checked state
 * @prop disabled - Disables the checkbox
 * @prop required - Makes the checkbox required
 * @prop name - Name attribute for form submission
 * @prop value - Value attribute for form submission
 * @prop class - CSS class names for the checkbox
 * @event update:checked - Emitted when the checked state changes
 */
const props = defineProps<CheckboxRootProps & {
  /** Controlled checked state. */
  checked?: boolean
  /** Default checked state. */
  defaultChecked?: boolean
  /** Disables the checkbox. */
  disabled?: boolean
  /** Makes the checkbox required. */
  required?: boolean
  /** Name attribute for form submission. */
  name?: string
  /** Value attribute for form submission. */
  value?: string
  /** CSS class names for the checkbox. */
  class?: HTMLAttributes['class']
}>()
const emits = defineEmits<CheckboxRootEmits>()
</script>

<template>
  <CheckboxRoot
    v-bind="props"
    :class="cn(
      'peer h-4 w-4 shrink-0 rounded-sm border border-primary ring-offset-background focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:cursor-not-allowed disabled:opacity-50 data-[state=checked]:bg-primary data-[state=checked]:text-primary-foreground',
      props.class
    )"
    @update:checked="emits('update:checked', $event)"
  >
    <CheckboxIndicator class="flex items-center justify-center text-current">
      <Check class="h-4 w-4" />
    </CheckboxIndicator>
  </CheckboxRoot>
</template>
