// packages/vue/src/blocks/chat-ui/ChatMessage.vue
<script setup lang="ts">
import { computed, type HTMLAttributes } from 'vue'
import Avatar from '@/components/avatar/avatar.vue'
import AvatarImage from '@/components/avatar/avatar-image.vue'
import AvatarFallback from '@/components/avatar/avatar-fallback.vue'
import { cn } from '@/lib/utils'
import type { Message } from './types'

interface Props {
  message: Message
  showTimestamp?: boolean
  class?: HTMLAttributes['class']
}

const props = withDefaults(defineProps<Props>(), {
  showTimestamp: true,
})

const formattedTime = computed(() => {
  const date = props.message.timestamp
  return date.toLocaleTimeString('en-US', {
    hour: '2-digit',
    minute: '2-digit'
  })
})

const initials = computed(() => {
  return props.message.senderName
    .split(' ')
    .map(n => n[0])
    .join('')
    .toUpperCase()
    .slice(0, 2)
})
</script>

<template>
  <div
    :class="cn(
      'flex gap-3 mb-4',
      message.isCurrentUser && 'flex-row-reverse',
      props.class
    )"
  >
    <Avatar class="h-8 w-8">
      <AvatarImage v-if="message.senderAvatar" :src="message.senderAvatar" :alt="message.senderName" />
      <AvatarFallback>{{ initials }}</AvatarFallback>
    </Avatar>

    <div
      :class="cn(
        'flex flex-col gap-1 max-w-[70%]',
        message.isCurrentUser && 'items-end'
      )"
    >
      <div class="flex items-center gap-2">
        <span
          :class="cn(
            'text-sm font-medium',
            message.isCurrentUser && 'order-2'
          )"
        >
          {{ message.senderName }}
        </span>
        <span
          v-if="showTimestamp"
          :class="cn(
            'text-xs text-muted-foreground',
            message.isCurrentUser && 'order-1'
          )"
        >
          {{ formattedTime }}
        </span>
      </div>

      <div
        :class="cn(
          'rounded-lg px-4 py-2 text-sm',
          message.isCurrentUser
            ? 'bg-primary text-primary-foreground'
            : 'bg-muted'
        )"
      >
        {{ message.content }}
      </div>
    </div>
  </div>
</template>

// packages/react-native/src/blocks/chat-ui/ChatMessage.tsx
import React from 'react'
import { View, Text, StyleSheet } from 'react-native'
import { Avatar } from '@/components/avatar'
import type { Message } from './types'

interface ChatMessageProps {
  message: Message
  showTimestamp?: boolean
}

export const ChatMessage: React.FC<ChatMessageProps> = ({
  message,
  showTimestamp = true,
}) => {
  const formattedTime = message.timestamp.toLocaleTimeString('en-US', {
    hour: '2-digit',
    minute: '2-digit',
  })

  const initials = message.senderName
    .split(' ')
    .map((n) => n[0])
    .join('')
    .toUpperCase()
    .slice(0, 2)

  return (
    <View
      style={[
        styles.container,
        message.isCurrentUser && styles.containerReverse,
      ]}
    >
      <Avatar
        src={message.senderAvatar}
        alt={message.senderName}
        fallback={initials}
        size="sm"
      />

      <View
        style={[
          styles.content,
          message.isCurrentUser && styles.contentEnd,
        ]}
      >
        <View
          style={[
            styles.header,
            message.isCurrentUser && styles.headerReverse,
          ]}
        >
          <Text style={styles.senderName}>{message.senderName}</Text>
          {showTimestamp && (
            <Text style={styles.timestamp}>{formattedTime}</Text>
          )}
        </View>

        <View
          style={[
            styles.bubble,
            message.isCurrentUser
              ? styles.bubbleCurrentUser
              : styles.bubbleOtherUser,
          ]}
        >
          <Text
            style={[
              styles.messageText,
              message.isCurrentUser && styles.messageTextCurrentUser,
            ]}
          >
            {message.content}
          </Text>
        </View>
      </View>
    </View>
  )
}

const styles = StyleSheet.create({
  container: {
    flexDirection: 'row',
    gap: 12,
    marginBottom: 16,
  },
  containerReverse: {
    flexDirection: 'row-reverse',
  },
  avatar: {
    width: 32,
    height: 32,
  },
  content: {
    flex: 1,
    maxWidth: '70%',
  },
  contentEnd: {
    alignItems: 'flex-end',
  },
  header: {
    flexDirection: 'row',
    gap: 8,
    marginBottom: 4,
  },
  headerReverse: {
    flexDirection: 'row-reverse',
  },
  senderName: {
    fontSize: 14,
    fontWeight: '500',
  },
  timestamp: {
    fontSize: 12,
    color: '#666',
  },
  bubble: {
    borderRadius: 12,
    paddingHorizontal: 16,
    paddingVertical: 10,
  },
  bubbleCurrentUser: {
    backgroundColor: '#007AFF',
  },
  bubbleOtherUser: {
    backgroundColor: '#E5E5EA',
  },
  messageText: {
    fontSize: 15,
  },
  messageTextCurrentUser: {
    color: '#FFFFFF',
  },
})
