// examples/react-admin-dashboard/src/pages/DashboardHome.tsx
import { Card, CardHeader, CardTitle, CardDescription, CardContent } from '@/components/ui/card'
import { Badge } from '@/components/ui/badge'

export function DashboardHome() {
  return (
    <div className="space-y-6">
      <div>
        <h1 className="text-3xl font-bold">Admin Dashboard</h1>
        <p className="text-gray-500 mt-2">Welcome to Galaxy UI Admin Dashboard</p>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
        <Card>
          <CardHeader>
            <CardTitle>Form Components</CardTitle>
            <CardDescription>Input, Button, Checkbox, etc.</CardDescription>
          </CardHeader>
          <CardContent>
            <Badge>13 Components</Badge>
          </CardContent>
        </Card>

        <Card>
          <CardHeader>
            <CardTitle>Data Display</CardTitle>
            <CardDescription>Table, Badge, Avatar, etc.</CardDescription>
          </CardHeader>
          <CardContent>
            <Badge>15 Components</Badge>
          </CardContent>
        </Card>

        <Card>
          <CardHeader>
            <CardTitle>Feedback</CardTitle>
            <CardDescription>Alert, Toast, Dialog, etc.</CardDescription>
          </CardHeader>
          <CardContent>
            <Badge>10 Components</Badge>
          </CardContent>
        </Card>

        <Card>
          <CardHeader>
            <CardTitle>Navigation</CardTitle>
            <CardDescription>Tabs, Breadcrumb, Menu, etc.</CardDescription>
          </CardHeader>
          <CardContent>
            <Badge>8 Components</Badge>
          </CardContent>
        </Card>

        <Card>
          <CardHeader>
            <CardTitle>Layout</CardTitle>
            <CardDescription>Card, Separator, Accordion, etc.</CardDescription>
          </CardHeader>
          <CardContent>
            <Badge>12 Components</Badge>
          </CardContent>
        </Card>

        <Card>
          <CardHeader>
            <CardTitle>Charts</CardTitle>
            <CardDescription>Line, Bar, Pie, Scatter, etc.</CardDescription>
          </CardHeader>
          <CardContent>
            <Badge>8 Components</Badge>
          </CardContent>
        </Card>
      </div>

      <Card>
        <CardHeader>
          <CardTitle>Getting Started</CardTitle>
          <CardDescription>Quick guide to using the dashboard</CardDescription>
        </CardHeader>
        <CardContent className="space-y-4">
          <div>
            <h3 className="font-semibold mb-2">Navigation</h3>
            <p className="text-sm text-gray-600">
              Use the sidebar on the left to navigate between different component categories.
              Click on any menu item to view examples of that category.
            </p>
          </div>
          <div>
            <h3 className="font-semibold mb-2">Components</h3>
            <p className="text-sm text-gray-600">
              All components are built with Galaxy UI, a multi-framework UI library that supports
              React, Vue, Angular, and more.
            </p>
          </div>
          <div>
            <h3 className="font-semibold mb-2">Authentication</h3>
            <p className="text-sm text-gray-600">
              Default credentials: <code className="bg-gray-100 px-2 py-1 rounded">admin</code> /
              <code className="bg-gray-100 px-2 py-1 rounded ml-1">Abc123@</code>
            </p>
          </div>
        </CardContent>
      </Card>
    </div>
  )
}

// examples/angular-admin-dashboard/src/app/pages/dashboard-home.component.ts
import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { CardComponent, CardHeaderComponent, CardTitleComponent, CardDescriptionComponent, CardContentComponent } from '../../components/ui/card';

@Component({
  selector: 'app-dashboard-home',
  standalone: true,
  imports: [
    CommonModule,
    CardComponent,
    CardHeaderComponent,
    CardTitleComponent,
    CardDescriptionComponent,
    CardContentComponent
  ],
  template: `
    <div class="space-y-6">
      <div>
        <h2 class="text-3xl font-bold">Welcome to Galaxy UI Admin Dashboard</h2>
        <p class="text-gray-600 mt-2">
          Built with Angular 20 and Galaxy Design System
        </p>
      </div>

      <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
        <ui-card>
          <ui-card-header>
            <ui-card-title>📝 Form Components</ui-card-title>
            <ui-card-description>
              Input, Label, Checkbox and Form elements
            </ui-card-description>
          </ui-card-header>
          <ui-card-content>
            Explore various form components for building interactive forms.
          </ui-card-content>
        </ui-card>

        <ui-card>
          <ui-card-header>
            <ui-card-title>📈 Data Display</ui-card-title>
            <ui-card-description>
              Table, Badge, and Avatar components
            </ui-card-description>
          </ui-card-header>
          <ui-card-content>
            Display and organize data with tables and visual indicators.
          </ui-card-content>
        </ui-card>

        <ui-card>
          <ui-card-header>
            <ui-card-title>💬 Feedback</ui-card-title>
            <ui-card-description>
              Alert components for user feedback
            </ui-card-description>
          </ui-card-header>
          <ui-card-content>
            Provide feedback to users with various alert styles.
          </ui-card-content>
        </ui-card>

        <ui-card>
          <ui-card-header>
            <ui-card-title>🧭 Navigation</ui-card-title>
            <ui-card-description>
              Tabs and Breadcrumb components
            </ui-card-description>
          </ui-card-header>
          <ui-card-content>
            Build intuitive navigation with tabs and breadcrumbs.
          </ui-card-content>
        </ui-card>

        <ui-card>
          <ui-card-header>
            <ui-card-title>📐 Layout</ui-card-title>
            <ui-card-description>
              Card and Separator components
            </ui-card-description>
          </ui-card-header>
          <ui-card-content>
            Structure your content with flexible layout components.
          </ui-card-content>
        </ui-card>

        <ui-card>
          <ui-card-header>
            <ui-card-title>🎨 Components</ui-card-title>
            <ui-card-description>
              20+ UI components available
            </ui-card-description>
          </ui-card-header>
          <ui-card-content>
            Fully typed, accessible, and customizable components.
          </ui-card-content>
        </ui-card>
      </div>
    </div>
  `
})
export class DashboardHomeComponent {}
