// packages/vue/src/components/charts/GaugeChart.vue
<script setup lang="ts">
import { computed } from 'vue'
import VChart from 'vue-echarts'
import { use } from 'echarts/core'
import { GaugeChart } from 'echarts/charts'
import {
  TooltipComponent,
  LegendComponent,
} from 'echarts/components'
import { CanvasRenderer } from 'echarts/renderers'
import { cn } from '@/lib/utils'
import type { GaugeChartProps } from './types'

// Register ECharts components
use([
  GaugeChart,
  TooltipComponent,
  LegendComponent,
  CanvasRenderer,
])

export interface Props extends GaugeChartProps {
  class?: string
}

const props = withDefaults(defineProps<Props>(), {
  height: 300,
  width: '100%',
  theme: 'light',
  min: 0,
  max: 100,
  startAngle: 225,
  endAngle: -45,
  splitNumber: 5,
  showProgress: true,
  showPointer: true,
  loading: false,
  emptyText: 'No data available',
})

// Build ECharts option
const chartOption = computed(() => {
  if (props.value === null || props.value === undefined) {
    return null
  }

  // Build color zones or use default color
  let axisLineColors: Array<[number, string]>

  if (props.zones && props.zones.length > 0) {
    // Convert zones to ECharts format
    axisLineColors = props.zones.map(zone => [
      (zone.to - props.min!) / (props.max! - props.min!),
      zone.color
    ])
  } else if (Array.isArray(props.color)) {
    // Gradient colors
    const step = 1 / props.color.length
    axisLineColors = props.color.map((color, index) => [
      (index + 1) * step,
      color
    ])
  } else {
    // Single color or default
    const color = props.color || '#3b82f6'
    axisLineColors = [[1, color]]
  }

  const formatter = props.formatter || ((value: number) => `${value}${props.unit || ''}`)

  return {
    series: [
      {
        type: 'gauge',
        startAngle: props.startAngle,
        endAngle: props.endAngle,
        min: props.min,
        max: props.max,
        splitNumber: props.splitNumber,

        // Progress arc
        progress: props.showProgress ? {
          show: true,
          width: 18,
        } : undefined,

        // Pointer
        pointer: props.showPointer ? {
          show: true,
          length: '60%',
          width: 6,
        } : {
          show: false,
        },

        // Axis line (background arc)
        axisLine: {
          lineStyle: {
            width: 18,
            color: axisLineColors,
          },
        },

        // Axis tick
        axisTick: {
          show: true,
          distance: -18,
          length: 5,
          lineStyle: {
            color: props.theme === 'dark' ? '#4b5563' : '#d1d5db',
            width: 1,
          },
        },

        // Split line
        splitLine: {
          show: true,
          distance: -18,
          length: 10,
          lineStyle: {
            color: props.theme === 'dark' ? '#4b5563' : '#d1d5db',
            width: 2,
          },
        },

        // Axis label
        axisLabel: {
          show: true,
          distance: 25,
          color: props.theme === 'dark' ? '#9ca3af' : '#6b7280',
          fontSize: 11,
        },

        // Anchor (center circle)
        anchor: {
          show: props.showPointer,
          showAbove: true,
          size: 15,
          itemStyle: {
            borderWidth: 2,
            borderColor: props.theme === 'dark' ? '#4b5563' : '#d1d5db',
          },
        },

        // Title
        title: {
          show: !!props.title,
          offsetCenter: [0, '80%'],
          fontSize: 14,
          color: props.theme === 'dark' ? '#9ca3af' : '#6b7280',
        },

        // Detail (value display)
        detail: {
          valueAnimation: props.animation !== false,
          formatter: formatter,
          fontSize: 28,
          fontWeight: 'bold',
          color: props.theme === 'dark' ? '#fafafa' : '#0a0a0a',
          offsetCenter: [0, '10%'],
        },

        data: [
          {
            value: props.value,
            name: props.title || '',
          },
        ],
      },
    ],
  }
})

// Get responsive dimensions
const dimensions = computed(() => ({
  height: `${props.height}px`,
  width: typeof props.width === 'number' ? `${props.width}px` : props.width,
}))
</script>

<template>
  <div :class="cn('galaxy-gauge-chart w-full', props.class)">
    <!-- Loading State -->
    <div
      v-if="loading"
      class="flex items-center justify-center bg-gray-50 dark:bg-gray-900 rounded-lg border border-gray-200 dark:border-gray-700"
      :style="{ height: dimensions.height }"
    >
      <div class="animate-spin rounded-full h-8 w-8 border-b-2 border-primary"></div>
    </div>

    <!-- Empty State -->
    <div
      v-else-if="!chartOption"
      class="flex items-center justify-center bg-gray-50 dark:bg-gray-900 rounded-lg border border-gray-200 dark:border-gray-700"
      :style="{ height: dimensions.height }"
    >
      <p class="text-gray-500 dark:text-gray-400">{{ emptyText }}</p>
    </div>

    <!-- Chart -->
    <VChart
      v-else
      :option="chartOption"
      :style="dimensions"
      :theme="theme"
      autoresize
    />
  </div>
</template>

<style scoped>
.galaxy-gauge-chart {
  position: relative;
}

/* Dark mode support */
:deep(.dark) .galaxy-gauge-chart {
  color-scheme: dark;
}
</style>

// packages/angular/src/components/charts/gauge-chart.component.ts
import { Component, Input, OnInit, OnChanges, SimpleChanges } from '@angular/core'
import { CommonModule } from '@angular/common'
import { NgxEchartsModule } from 'ngx-echarts'
import type { EChartsOption } from 'echarts'
import type { GaugeChartProps } from './types'

@Component({
  selector: 'ui-gauge-chart',
  standalone: true,
  imports: [CommonModule, NgxEchartsModule],
  template: `
    <div [class]="containerClass">
      <!-- Loading state -->
      <div
        *ngIf="loading"
        [style.height]="dimensions.height"
        class="flex items-center justify-center"
      >
        <div class="animate-spin rounded-full h-8 w-8 border-b-2 border-primary"></div>
      </div>

      <!-- Empty state -->
      <div
        *ngIf="!chartOption && !loading"
        [style.height]="dimensions.height"
        class="flex items-center justify-center border border-border rounded-md"
      >
        <p class="text-muted-foreground text-sm">{{ emptyText }}</p>
      </div>

      <!-- Chart -->
      <div
        *ngIf="chartOption && !loading"
        echarts
        [options]="chartOption"
        [theme]="theme"
        [loading]="loading"
        [style.height]="dimensions.height"
        [style.width]="dimensions.width"
        class="galaxy-gauge-chart"
      ></div>
    </div>
  `,
  styles: [
    `
      :host {
        display: block;
        width: 100%;
      }
    `,
  ],
})
export class GaugeChartComponent implements OnInit, OnChanges, GaugeChartProps {
  @Input({ required: true }) value!: number
  @Input() height: number = 300
  @Input() width?: number | string = '100%'
  @Input() theme: 'light' | 'dark' = 'light'
  @Input() min: number = 0
  @Input() max: number = 100
  @Input() startAngle: number = 225
  @Input() endAngle: number = -45
  @Input() splitNumber: number = 5
  @Input() showProgress: boolean = true
  @Input() showPointer: boolean = true
  @Input() title?: string
  @Input() unit?: string
  @Input() zones?: Array<{ from: number; to: number; color: string }>
  @Input() color?: string | string[]
  @Input() formatter?: (value: number) => string
  @Input() animation: boolean = true
  @Input() loading: boolean = false
  @Input() emptyText: string = 'No data available'
  @Input() class?: string

  chartOption: EChartsOption | null = null
  dimensions: { width: string; height: string } = { width: '100%', height: '300px' }

  get containerClass(): string {
    return `galaxy-gauge-chart-container w-full ${this.class || ''}`
  }

  ngOnInit(): void {
    this.updateChart()
    this.updateDimensions()
  }

  ngOnChanges(changes: SimpleChanges): void {
    if (changes['value'] || changes['theme'] || changes['zones'] || changes['color']) {
      this.updateChart()
    }
    if (changes['width'] || changes['height']) {
      this.updateDimensions()
    }
  }

  private updateChart(): void {
    if (this.value === null || this.value === undefined) {
      this.chartOption = null
      return
    }

    // Build color zones or use default color
    let axisLineColors: Array<[number, string]>

    if (this.zones && this.zones.length > 0) {
      // Convert zones to ECharts format
      axisLineColors = this.zones.map(zone => [
        (zone.to - this.min) / (this.max - this.min),
        zone.color
      ])
    } else if (Array.isArray(this.color)) {
      // Gradient colors
      const step = 1 / this.color.length
      axisLineColors = this.color.map((c, index) => [
        (index + 1) * step,
        c
      ])
    } else {
      // Single color or default
      const c = this.color || '#3b82f6'
      axisLineColors = [[1, c]]
    }

    const valueFormatter = this.formatter || ((v: number) => `${v}${this.unit || ''}`)

    this.chartOption = {
      series: [
        {
          type: 'gauge',
          startAngle: this.startAngle,
          endAngle: this.endAngle,
          min: this.min,
          max: this.max,
          splitNumber: this.splitNumber,

          // Progress arc
          progress: this.showProgress ? {
            show: true,
            width: 18,
          } : undefined,

          // Pointer
          pointer: this.showPointer ? {
            show: true,
            length: '60%',
            width: 6,
          } : {
            show: false,
          },

          // Axis line (background arc)
          axisLine: {
            lineStyle: {
              width: 18,
              color: axisLineColors,
            },
          },

          // Axis tick
          axisTick: {
            show: true,
            distance: -18,
            length: 5,
            lineStyle: {
              color: this.theme === 'dark' ? '#4b5563' : '#d1d5db',
              width: 1,
            },
          },

          // Split line
          splitLine: {
            show: true,
            distance: -18,
            length: 10,
            lineStyle: {
              color: this.theme === 'dark' ? '#4b5563' : '#d1d5db',
              width: 2,
            },
          },

          // Axis label
          axisLabel: {
            show: true,
            distance: 25,
            color: this.theme === 'dark' ? '#9ca3af' : '#6b7280',
            fontSize: 11,
          },

          // Anchor (center circle)
          anchor: {
            show: this.showPointer,
            showAbove: true,
            size: 15,
            itemStyle: {
              borderWidth: 2,
              borderColor: this.theme === 'dark' ? '#4b5563' : '#d1d5db',
            },
          },

          // Title
          title: {
            show: !!this.title,
            offsetCenter: [0, '80%'],
            fontSize: 14,
            color: this.theme === 'dark' ? '#9ca3af' : '#6b7280',
          },

          // Detail (value display)
          detail: {
            valueAnimation: this.animation,
            formatter: valueFormatter,
            fontSize: 28,
            fontWeight: 'bold',
            color: this.theme === 'dark' ? '#fafafa' : '#0a0a0a',
            offsetCenter: [0, '10%'],
          },

          data: [
            {
              value: this.value,
              name: this.title || '',
            },
          ],
        } as any,
      ],
    }
  }

  private updateDimensions(): void {
    this.dimensions = {
      height: `${this.height}px`,
      width: typeof this.width === 'number' ? `${this.width}px` : this.width,
    }
  }
}
