// packages/vue/src/components/switch/Switch.vue
<!--
 * @author Bùi Trọng Hiếu
 * @email kevinbui210191@gmail.com
 * @desc Switch component - Toggle switch for binary on/off state
-->
<script setup lang="ts">
import { SwitchRoot, SwitchThumb, type SwitchRootProps } from 'radix-vue'
import { cn } from '@/lib/utils'

/**
 * Switch Props
 * @prop checked - Controlled checked state
 * @prop defaultChecked - Default checked state
 * @prop disabled - Disables the switch
 * @prop required - Makes the switch required
 * @prop name - Name attribute for form submission
 * @prop value - Value attribute for form submission
 * @prop class - CSS class names for the switch
 */
const props = defineProps<SwitchRootProps & {
  /** Controlled checked state. */
  checked?: boolean
  /** Default checked state. */
  defaultChecked?: boolean
  /** Disables the switch. */
  disabled?: boolean
  /** Makes the switch required. */
  required?: boolean
  /** Name attribute for form submission. */
  name?: string
  /** Value attribute for form submission. */
  value?: string
  /** CSS class names for the switch. */
  class?: string
}>()
</script>

<template>
  <SwitchRoot
    v-bind="props"
    :class="cn(
      'peer inline-flex h-6 w-11 shrink-0 cursor-pointer items-center rounded-full border-2 border-transparent transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 focus-visible:ring-offset-background disabled:cursor-not-allowed disabled:opacity-50 data-[state=checked]:bg-primary data-[state=unchecked]:bg-input',
      props.class
    )"
  >
    <SwitchThumb
      class="pointer-events-none block h-5 w-5 rounded-full bg-background shadow-lg ring-0 transition-transform data-[state=checked]:translate-x-5 data-[state=unchecked]:translate-x-0"
    />
  </SwitchRoot>
</template>

// packages/angular/src/components/switch/switch.component.ts
/**
 * @author Bùi Trọng Hiếu
 * @email kevinbui210191@gmail.com
 * @desc Toggle switch for binary on/off states
 */

import { Component, Input, Output, EventEmitter, ChangeDetectionStrategy } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RdxSwitchInputDirective, RdxSwitchRootDirective, RdxSwitchThumbDirective } from '@radix-ng/primitives/switch';
import { cn } from '@/lib/utils';

@Component({
  selector: 'ui-switch',
  standalone: true,
  imports: [CommonModule, RdxSwitchRootDirective, RdxSwitchInputDirective, RdxSwitchThumbDirective],
  template: `
    <button
      rdxSwitchRoot
      type="button"
      [class]="switchClasses"
      [id]="id || null"
      [required]="required"
      [defaultChecked]="defaultChecked"
      [checked]="checked"
      (checkedChange)="handleCheckedChange($event)"
      [disabled]="disabled"
      [aria-label]="ariaLabel || null"
      [aria-labelledby]="ariaLabelledBy || null"
    >
      <input rdxSwitchInput type="checkbox" class="sr-only" />
      <span rdxSwitchThumb [class]="thumbClasses"></span>
    </button>
  `,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class SwitchComponent {
  @Input() id?: string;
  @Input() required: boolean = false;
  @Input() ariaLabel?: string;
  @Input() ariaLabelledBy?: string;
  @Input() defaultChecked: boolean = false;
  @Input() checked: boolean = false;
  @Input() disabled: boolean = false;
  @Input() class?: string;
  @Output() checkedChange = new EventEmitter<boolean>();

  handleCheckedChange(checked: boolean): void {
    this.checked = checked;
    this.checkedChange.emit(checked);
  }

  get switchClasses(): string {
    return cn(
      'peer inline-flex h-6 w-11 shrink-0 cursor-pointer items-center rounded-full border-2 border-transparent transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:cursor-not-allowed disabled:opacity-50',
      this.checked ? 'bg-primary' : 'bg-input',
      this.class
    );
  }

  get thumbClasses(): string {
    return cn(
      'pointer-events-none block h-5 w-5 rounded-full bg-background shadow-lg ring-0 transition-transform',
      this.checked ? 'translate-x-5' : 'translate-x-0'
    );
  }
}
