// packages/react-native/src/components/alert-dialog/AlertDialog.tsx
/**
 * @author Bùi Trọng Hiếu
 * @email kevinbui210191@gmail.com
 * @desc Alert dialog component for displaying confirmation dialogs with actions
 */

import * as React from 'react';
import * as AlertDialogPrimitive from '@rn-primitives/alert-dialog';
import { View, Text } from 'react-native';
import { cn } from '@/lib/utils';

const AlertDialog = AlertDialogPrimitive.Root;

const AlertDialogTrigger = AlertDialogPrimitive.Trigger;

const AlertDialogPortal = AlertDialogPrimitive.Portal;

const AlertDialogOverlay = React.forwardRef<
  React.ElementRef<typeof AlertDialogPrimitive.Overlay>,
  React.ComponentPropsWithoutRef<typeof AlertDialogPrimitive.Overlay>
>(({ className, ...props }, ref) => (
  <AlertDialogPrimitive.Overlay
    className={cn(
      'fixed inset-0 z-50 bg-background/80 backdrop-blur-sm',
      'data-[state=open]:animate-in data-[state=closed]:animate-out data-[state=closed]:fade-out-0 data-[state=open]:fade-in-0',
      className
    )}
    {...props}
    ref={ref}
  />
));
AlertDialogOverlay.displayName = AlertDialogPrimitive.Overlay.displayName;

const AlertDialogContent = React.forwardRef<
  React.ElementRef<typeof AlertDialogPrimitive.Content>,
  React.ComponentPropsWithoutRef<typeof AlertDialogPrimitive.Content>
>(({ className, ...props }, ref) => (
  <AlertDialogPortal>
    <AlertDialogOverlay />
    <AlertDialogPrimitive.Content
      ref={ref}
      className={cn(
        'fixed left-1/2 top-1/2 z-50 grid w-full max-w-lg -translate-x-1/2 -translate-y-1/2 gap-4 border border-border bg-background p-6 shadow-lg',
        'web:duration-200',
        'data-[state=open]:animate-in data-[state=closed]:animate-out data-[state=closed]:fade-out-0 data-[state=open]:fade-in-0 data-[state=closed]:zoom-out-95 data-[state=open]:zoom-in-95 data-[state=closed]:slide-out-to-left-1/2 data-[state=closed]:slide-out-to-top-[48%] data-[state=open]:slide-in-from-left-1/2 data-[state=open]:slide-in-from-top-[48%]',
        'rounded-lg',
        className
      )}
      {...props}
    />
  </AlertDialogPortal>
));
AlertDialogContent.displayName = AlertDialogPrimitive.Content.displayName;

const AlertDialogHeader = ({
  className,
  ...props
}: React.ComponentPropsWithoutRef<typeof View>) => (
  <View
    className={cn('flex flex-col gap-2 text-center sm:text-left', className)}
    {...props}
  />
);
AlertDialogHeader.displayName = 'AlertDialogHeader';

const AlertDialogFooter = ({
  className,
  ...props
}: React.ComponentPropsWithoutRef<typeof View>) => (
  <View
    className={cn('flex flex-col-reverse sm:flex-row sm:justify-end sm:gap-2', className)}
    {...props}
  />
);
AlertDialogFooter.displayName = 'AlertDialogFooter';

const AlertDialogTitle = React.forwardRef<
  React.ElementRef<typeof AlertDialogPrimitive.Title>,
  React.ComponentPropsWithoutRef<typeof AlertDialogPrimitive.Title>
>(({ className, ...props }, ref) => (
  <AlertDialogPrimitive.Title
    ref={ref}
    className={cn('text-lg font-semibold', className)}
    {...props}
  />
));
AlertDialogTitle.displayName = AlertDialogPrimitive.Title.displayName;

const AlertDialogDescription = React.forwardRef<
  React.ElementRef<typeof AlertDialogPrimitive.Description>,
  React.ComponentPropsWithoutRef<typeof AlertDialogPrimitive.Description>
>(({ className, ...props }, ref) => (
  <AlertDialogPrimitive.Description
    ref={ref}
    className={cn('text-sm text-muted-foreground', className)}
    {...props}
  />
));
AlertDialogDescription.displayName =
  AlertDialogPrimitive.Description.displayName;

const AlertDialogAction = React.forwardRef<
  React.ElementRef<typeof AlertDialogPrimitive.Action>,
  React.ComponentPropsWithoutRef<typeof AlertDialogPrimitive.Action>
>(({ className, ...props }, ref) => (
  <AlertDialogPrimitive.Action
    ref={ref}
    className={cn(
      'inline-flex h-10 items-center justify-center rounded-md bg-primary px-4 py-2 text-sm font-semibold text-primary-foreground',
      'web:ring-offset-background web:transition-colors web:hover:bg-primary/90 web:focus-visible:outline-none web:focus-visible:ring-2 web:focus-visible:ring-ring web:focus-visible:ring-offset-2',
      'disabled:pointer-events-none disabled:opacity-50',
      className
    )}
    {...props}
  />
));
AlertDialogAction.displayName = AlertDialogPrimitive.Action.displayName;

const AlertDialogCancel = React.forwardRef<
  React.ElementRef<typeof AlertDialogPrimitive.Cancel>,
  React.ComponentPropsWithoutRef<typeof AlertDialogPrimitive.Cancel>
>(({ className, ...props }, ref) => (
  <AlertDialogPrimitive.Cancel
    ref={ref}
    className={cn(
      'mt-2 inline-flex h-10 items-center justify-center rounded-md border border-input bg-background px-4 py-2 text-sm font-semibold',
      'web:ring-offset-background web:transition-colors web:hover:bg-accent web:hover:text-accent-foreground web:focus-visible:outline-none web:focus-visible:ring-2 web:focus-visible:ring-ring web:focus-visible:ring-offset-2',
      'disabled:pointer-events-none disabled:opacity-50',
      'sm:mt-0',
      className
    )}
    {...props}
  />
));
AlertDialogCancel.displayName = AlertDialogPrimitive.Cancel.displayName;

export {
  AlertDialog,
  AlertDialogPortal,
  AlertDialogOverlay,
  AlertDialogTrigger,
  AlertDialogContent,
  AlertDialogHeader,
  AlertDialogFooter,
  AlertDialogTitle,
  AlertDialogDescription,
  AlertDialogAction,
  AlertDialogCancel,
};

// packages/angular/src/components/alert-dialog/alert-dialog.component.ts
/**
 * @author Bùi Trọng Hiếu
 * @email kevinbui210191@gmail.com
 * @desc Alert Dialog component - Modal dialog for alerts and confirmations
 */

import { Component, Input, Output, EventEmitter, ChangeDetectionStrategy, TemplateRef, ViewChild } from '@angular/core';
import { CommonModule } from '@angular/common';
import {
  RdxAlertDialogRootDirective,
  RdxAlertDialogTriggerDirective,
  RdxAlertDialogContentDirective,
  RdxAlertDialogTitleDirective,
  RdxAlertDialogCancelDirective,
} from '@radix-ng/primitives/alert-dialog';
import { cn } from '../../lib/utils';

@Component({
  selector: 'ui-alert-dialog',
  standalone: true,
  imports: [CommonModule, RdxAlertDialogRootDirective],
  template: `
    <ng-template #dialogContent>
      <ng-content></ng-content>
    </ng-template>
    <div rdxAlertDialogRoot [content]="dialogContent"></div>
  `,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class AlertDialogComponent {
  @Input() open = false;
  @Output() openChange = new EventEmitter<boolean>();
  @ViewChild('dialogContent', { static: true }) dialogContent!: TemplateRef<unknown>;
}

@Component({
  selector: 'ui-alert-dialog-trigger',
  standalone: true,
  imports: [CommonModule, RdxAlertDialogTriggerDirective],
  template: `<button rdxAlertDialogTrigger [class]="triggerClasses"><ng-content></ng-content></button>`,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class AlertDialogTriggerComponent {
  @Input() class?: string;
  get triggerClasses(): string { return cn('', this.class); }
}

@Component({
  selector: 'ui-alert-dialog-content',
  standalone: true,
  imports: [CommonModule, RdxAlertDialogContentDirective],
  template: `
    <div rdxAlertDialogContent [class]="contentClasses">
      <ng-content></ng-content>
    </div>
  `,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class AlertDialogContentComponent {
  @Input() class?: string;
  get contentClasses(): string {
    return cn('fixed left-[50%] top-[50%] z-50 grid w-full max-w-lg translate-x-[-50%] translate-y-[-50%] gap-4 border bg-background p-6 shadow-lg duration-200 data-[state=open]:animate-in data-[state=closed]:animate-out data-[state=closed]:fade-out-0 data-[state=open]:fade-in-0 data-[state=closed]:zoom-out-95 data-[state=open]:zoom-in-95 sm:rounded-lg', this.class);
  }
}

@Component({
  selector: 'ui-alert-dialog-title',
  standalone: true,
  imports: [CommonModule, RdxAlertDialogTitleDirective],
  template: `<h2 rdxAlertDialogTitle [class]="titleClasses"><ng-content></ng-content></h2>`,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class AlertDialogTitleComponent {
  @Input() class?: string;
  get titleClasses(): string { return cn('text-lg font-semibold', this.class); }
}

@Component({
  selector: 'ui-alert-dialog-description',
  standalone: true,
  imports: [CommonModule],
  template: `<p [class]="descClasses"><ng-content></ng-content></p>`,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class AlertDialogDescriptionComponent {
  @Input() class?: string;
  get descClasses(): string { return cn('text-sm text-muted-foreground', this.class); }
}

@Component({
  selector: 'ui-alert-dialog-action',
  standalone: true,
  imports: [CommonModule, RdxAlertDialogCancelDirective],
  template: `<button rdxAlertDialogCancel [class]="actionClasses"><ng-content></ng-content></button>`,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class AlertDialogActionComponent {
  @Input() class?: string;
  get actionClasses(): string { return cn('', this.class); }
}

@Component({
  selector: 'ui-alert-dialog-cancel',
  standalone: true,
  imports: [CommonModule, RdxAlertDialogCancelDirective],
  template: `<button rdxAlertDialogCancel [class]="cancelClasses"><ng-content></ng-content></button>`,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class AlertDialogCancelComponent {
  @Input() class?: string;
  get cancelClasses(): string { return cn('', this.class); }
}

@Component({
  selector: 'ui-alert-dialog-header',
  standalone: true,
  imports: [CommonModule],
  template: `<div [class]="headerClasses"><ng-content></ng-content></div>`,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class AlertDialogHeaderComponent {
  @Input() class?: string;
  get headerClasses(): string { return cn('flex flex-col space-y-2 text-center sm:text-left', this.class); }
}

@Component({
  selector: 'ui-alert-dialog-footer',
  standalone: true,
  imports: [CommonModule],
  template: `<div [class]="footerClasses"><ng-content></ng-content></div>`,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class AlertDialogFooterComponent {
  @Input() class?: string;
  get footerClasses(): string { return cn('flex flex-col-reverse sm:flex-row sm:justify-end sm:space-x-2', this.class); }
}
