// examples/nuxt-fresh-test/components/ui/authentication/RegisterForm.vue
<script setup lang="ts">
import { ref, type HTMLAttributes } from 'vue'
import Button from '@/components/ui/button/Button.vue'
import Input from '@/components/ui/input/Input.vue'
import Label from '@/components/ui/label/label.vue'
import Checkbox from '@/components/ui/checkbox/checkbox.vue'
import { cn } from '@/lib/utils'
import type { RegisterFormData } from './types'

interface Props {
  loading?: boolean
  error?: string
  class?: HTMLAttributes['class']
}

const props = withDefaults(defineProps<Props>(), {
  loading: false,
})

const emit = defineEmits<{
  submit: [data: RegisterFormData]
}>()

const formData = ref<RegisterFormData>({
  name: '',
  email: '',
  password: '',
  confirmPassword: '',
  acceptTerms: false,
})

const errors = ref<Partial<Record<keyof RegisterFormData, string>>>({})

const validate = (): boolean => {
  errors.value = {}

  if (!formData.value.name) {
    errors.value.name = 'Name is required'
  }

  if (!formData.value.email) {
    errors.value.email = 'Email is required'
  } else if (!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(formData.value.email)) {
    errors.value.email = 'Invalid email format'
  }

  if (!formData.value.password) {
    errors.value.password = 'Password is required'
  } else if (formData.value.password.length < 8) {
    errors.value.password = 'Password must be at least 8 characters'
  }

  if (!formData.value.confirmPassword) {
    errors.value.confirmPassword = 'Please confirm your password'
  } else if (formData.value.password !== formData.value.confirmPassword) {
    errors.value.confirmPassword = 'Passwords do not match'
  }

  if (!formData.value.acceptTerms) {
    errors.value.acceptTerms = 'You must accept the terms and conditions'
  }

  return Object.keys(errors.value).length === 0
}

const handleSubmit = () => {
  if (validate()) {
    emit('submit', formData.value)
  }
}
</script>

<template>
  <form
    :class="cn('space-y-4', props.class)"
    @submit.prevent="handleSubmit"
  >
    <!-- Name -->
    <div class="space-y-2">
      <Label for="name">Full Name</Label>
      <Input
        id="name"
        v-model="formData.name"
        type="text"
        placeholder="John Doe"
        :disabled="loading"
        :class="errors.name && 'border-destructive'"
      />
      <p v-if="errors.name" class="text-sm text-destructive">
        {{ errors.name }}
      </p>
    </div>

    <!-- Email -->
    <div class="space-y-2">
      <Label for="email">Email</Label>
      <Input
        id="email"
        v-model="formData.email"
        type="email"
        placeholder="name@example.com"
        :disabled="loading"
        :class="errors.email && 'border-destructive'"
      />
      <p v-if="errors.email" class="text-sm text-destructive">
        {{ errors.email }}
      </p>
    </div>

    <!-- Password -->
    <div class="space-y-2">
      <Label for="password">Password</Label>
      <Input
        id="password"
        v-model="formData.password"
        type="password"
        :disabled="loading"
        :class="errors.password && 'border-destructive'"
      />
      <p v-if="errors.password" class="text-sm text-destructive">
        {{ errors.password }}
      </p>
    </div>

    <!-- Confirm Password -->
    <div class="space-y-2">
      <Label for="confirmPassword">Confirm Password</Label>
      <Input
        id="confirmPassword"
        v-model="formData.confirmPassword"
        type="password"
        :disabled="loading"
        :class="errors.confirmPassword && 'border-destructive'"
      />
      <p v-if="errors.confirmPassword" class="text-sm text-destructive">
        {{ errors.confirmPassword }}
      </p>
    </div>

    <!-- Terms -->
    <div class="space-y-2">
      <div class="flex items-start space-x-2">
        <Checkbox
          id="terms"
          v-model:checked="formData.acceptTerms"
          :disabled="loading"
          :class="errors.acceptTerms && 'border-destructive'"
        />
        <Label for="terms" class="text-sm font-normal cursor-pointer leading-tight">
          I accept the <a href="#" class="text-primary hover:underline">terms and conditions</a>
        </Label>
      </div>
      <p v-if="errors.acceptTerms" class="text-sm text-destructive">
        {{ errors.acceptTerms }}
      </p>
    </div>

    <!-- Error Message -->
    <div v-if="error" class="p-3 text-sm text-destructive bg-destructive/10 rounded-md">
      {{ error }}
    </div>

    <!-- Submit Button -->
    <Button type="submit" class="w-full" :disabled="loading">
      <svg
        v-if="loading"
        class="mr-2 h-4 w-4 animate-spin"
        xmlns="http://www.w3.org/2000/svg"
        fill="none"
        viewBox="0 0 24 24"
      >
        <circle class="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" stroke-width="4" />
        <path class="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z" />
      </svg>
      {{ loading ? 'Creating account...' : 'Create account' }}
    </Button>
  </form>
</template>

// packages/react/src/blocks/authentication/RegisterForm.tsx
import React, { useState } from 'react'
import { Button } from '@/components/ui/button/Button'
import { Input } from '@/components/ui/input/input'
import { Label } from '@/components/ui/label/label'
import { Checkbox } from '@/components/ui/checkbox/checkbox'
import { cn } from '@/lib/utils'
import type { RegisterFormData } from './types'

interface RegisterFormProps {
  onSubmit: (data: RegisterFormData) => void
  loading?: boolean
  error?: string
  className?: string
}

export const RegisterForm: React.FC<RegisterFormProps> = ({
  onSubmit,
  loading = false,
  error,
  className,
}) => {
  const [formData, setFormData] = useState<RegisterFormData>({
    name: '',
    email: '',
    password: '',
    confirmPassword: '',
    acceptTerms: false,
  })

  const [errors, setErrors] = useState<Partial<Record<keyof RegisterFormData, string>>>({})

  const validate = (): boolean => {
    const newErrors: Partial<Record<keyof RegisterFormData, string>> = {}

    if (!formData.name) newErrors.name = 'Name is required'

    if (!formData.email) {
      newErrors.email = 'Email is required'
    } else if (!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(formData.email)) {
      newErrors.email = 'Invalid email format'
    }

    if (!formData.password) {
      newErrors.password = 'Password is required'
    } else if (formData.password.length < 8) {
      newErrors.password = 'Password must be at least 8 characters'
    }

    if (!formData.confirmPassword) {
      newErrors.confirmPassword = 'Please confirm your password'
    } else if (formData.password !== formData.confirmPassword) {
      newErrors.confirmPassword = 'Passwords do not match'
    }

    if (!formData.acceptTerms) {
      newErrors.acceptTerms = 'You must accept the terms and conditions'
    }

    setErrors(newErrors)
    return Object.keys(newErrors).length === 0
  }

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault()
    if (validate()) {
      onSubmit(formData)
    }
  }

  return (
    <form onSubmit={handleSubmit} className={cn('space-y-4', className)}>
      {/* Name */}
      <div className="space-y-2">
        <Label htmlFor="name">Full Name</Label>
        <Input
          id="name"
          type="text"
          placeholder="John Doe"
          value={formData.name}
          onChange={(e) => setFormData({ ...formData, name: e.target.value })}
          disabled={loading}
          className={errors.name ? 'border-destructive' : ''}
        />
        {errors.name && <p className="text-sm text-destructive">{errors.name}</p>}
      </div>

      {/* Email */}
      <div className="space-y-2">
        <Label htmlFor="email">Email</Label>
        <Input
          id="email"
          type="email"
          placeholder="name@example.com"
          value={formData.email}
          onChange={(e) => setFormData({ ...formData, email: e.target.value })}
          disabled={loading}
          className={errors.email ? 'border-destructive' : ''}
        />
        {errors.email && <p className="text-sm text-destructive">{errors.email}</p>}
      </div>

      {/* Password */}
      <div className="space-y-2">
        <Label htmlFor="password">Password</Label>
        <Input
          id="password"
          type="password"
          value={formData.password}
          onChange={(e) => setFormData({ ...formData, password: e.target.value })}
          disabled={loading}
          className={errors.password ? 'border-destructive' : ''}
        />
        {errors.password && <p className="text-sm text-destructive">{errors.password}</p>}
      </div>

      {/* Confirm Password */}
      <div className="space-y-2">
        <Label htmlFor="confirmPassword">Confirm Password</Label>
        <Input
          id="confirmPassword"
          type="password"
          value={formData.confirmPassword}
          onChange={(e) => setFormData({ ...formData, confirmPassword: e.target.value })}
          disabled={loading}
          className={errors.confirmPassword ? 'border-destructive' : ''}
        />
        {errors.confirmPassword && (
          <p className="text-sm text-destructive">{errors.confirmPassword}</p>
        )}
      </div>

      {/* Terms */}
      <div className="space-y-2">
        <div className="flex items-start space-x-2">
          <Checkbox
            id="terms"
            checked={formData.acceptTerms}
            onCheckedChange={(checked) =>
              setFormData({ ...formData, acceptTerms: checked as boolean })
            }
            disabled={loading}
            className={errors.acceptTerms ? 'border-destructive' : ''}
          />
          <Label htmlFor="terms" className="text-sm font-normal cursor-pointer leading-tight">
            I accept the{' '}
            <a href="#" className="text-primary hover:underline">
              terms and conditions
            </a>
          </Label>
        </div>
        {errors.acceptTerms && (
          <p className="text-sm text-destructive">{errors.acceptTerms}</p>
        )}
      </div>

      {/* Error Message */}
      {error && (
        <div className="p-3 text-sm text-destructive bg-destructive/10 rounded-md">
          {error}
        </div>
      )}

      {/* Submit Button */}
      <Button type="submit" className="w-full" disabled={loading}>
        {loading && (
          <svg className="mr-2 h-4 w-4 animate-spin" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24">
            <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4" />
            <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z" />
          </svg>
        )}
        {loading ? 'Creating account...' : 'Create account'}
      </Button>
    </form>
  )
}
