// examples/rn-expo-admin/components/ui/label/Label.tsx
import * as React from 'react';
import { Text, TextProps } from 'react-native';
import { cn } from '@/lib/utils';

export interface LabelProps extends TextProps {
  required?: boolean;
}

const Label = React.forwardRef<React.ElementRef<typeof Text>, LabelProps>(
  ({ className, children, required, ...props }, ref) => {
    return (
      <Text
        ref={ref}
        className={cn(
          'text-sm font-medium text-foreground leading-none peer-disabled:cursor-not-allowed peer-disabled:opacity-70',
          className
        )}
        {...props}
      >
        {children}
        {required && <Text className="text-destructive ml-1">*</Text>}
      </Text>
    );
  }
);

Label.displayName = 'Label';

export { Label };

// examples/angular-test/src/components/ui/label/label.component.ts
import { Component, Input, HostBinding, ChangeDetectionStrategy } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RdxLabelDirective } from '@radix-ng/primitives/label';
import { cn } from '@/lib/utils';

@Component({
  selector: 'ui-label, label[ui-label]',
  standalone: true,
  imports: [CommonModule],
  template: `<ng-content></ng-content>`,
  hostDirectives: [RdxLabelDirective],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class LabelComponent {
  @Input() for?: string;
  @Input() class?: string;

  @HostBinding('class')
  get hostClasses(): string {
    return cn(
      'text-sm font-medium leading-none peer-disabled:cursor-not-allowed peer-disabled:opacity-70',
      this.class
    );
  }

  @HostBinding('attr.for')
  get forAttribute(): string | null {
    return this.for || null;
  }
}
