// packages/vue/src/components/slider/Slider.vue
<!--
 * @author Bùi Trọng Hiếu
 * @email kevinbui210191@gmail.com
 * @desc Slider component - Range slider input with min/max bounds and thumb control
-->
<script setup lang="ts">
import { type HTMLAttributes, computed } from 'vue'
import { SliderRange, SliderRoot, SliderThumb, SliderTrack, type SliderRootProps } from 'radix-vue'
import { cn } from '@/lib/utils'

/**
 * Slider Props
 * @prop modelValue - Controlled value
 * @prop defaultValue - Default value
 * @prop min - Minimum value
 * @prop max - Maximum value
 * @prop step - Step interval
 * @prop disabled - Disables the slider
 * @prop orientation - Slider orientation (horizontal or vertical)
 * @prop class - CSS class names for the slider
 */
interface Props extends SliderRootProps {
  /** Controlled value. */
  modelValue?: number[]
  /** Default value. */
  defaultValue?: number[]
  /** Minimum value. */
  min?: number
  /** Maximum value. */
  max?: number
  /** Step interval. */
  step?: number
  /** Disables the slider. */
  disabled?: boolean
  /** Slider orientation (horizontal or vertical). */
  orientation?: 'horizontal' | 'vertical'
  /** CSS class names for the slider. */
  class?: HTMLAttributes['class']
}

const props = defineProps<Props>()

const delegatedProps = computed(() => {
  const { class: _, ...delegated } = props
  return delegated
})
</script>

<template>
  <SliderRoot
    :class="cn('relative flex w-full touch-none select-none items-center', props.class)"
    v-bind="delegatedProps"
  >
    <SliderTrack class="relative h-2 w-full grow overflow-hidden rounded-full bg-secondary">
      <SliderRange class="absolute h-full bg-primary" />
    </SliderTrack>
    <SliderThumb
      class="block h-5 w-5 rounded-full border-2 border-primary bg-background ring-offset-background transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:pointer-events-none disabled:opacity-50"
    />
  </SliderRoot>
</template>

// packages/angular/src/components/slider/slider.component.ts
/**
 * @author Bùi Trọng Hiếu
 * @email kevinbui210191@gmail.com
 * @desc Range slider input with min/max bounds
 */

import { Component, Input, Output, EventEmitter, ChangeDetectionStrategy } from '@angular/core';
import { CommonModule } from '@angular/common';
import {
  RdxSliderRootComponent,
  RdxSliderTrackComponent,
  RdxSliderRangeComponent,
  RdxSliderThumbComponent,
} from '@radix-ng/primitives/slider';
import { cn } from '@/lib/utils';

@Component({
  selector: 'ui-slider',
  standalone: true,
  imports: [
    CommonModule,
    RdxSliderRootComponent,
    RdxSliderTrackComponent,
    RdxSliderRangeComponent,
    RdxSliderThumbComponent,
  ],
  template: `
    <rdx-slider
      [(modelValue)]="modelValue"
      [min]="min"
      [max]="max"
      [step]="step"
      [disabled]="disabled"
      (valueChange)="onValueChange($event)"
      [className]="sliderClasses"
    >
      <rdx-slider-track>
        <rdx-slider-range class="absolute h-full bg-primary"></rdx-slider-range>
      </rdx-slider-track>
      <rdx-slider-thumb class="block h-5 w-5 rounded-full border-2 border-primary bg-background ring-offset-background transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:pointer-events-none disabled:opacity-50"></rdx-slider-thumb>
    </rdx-slider>
  `,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class SliderComponent {
  @Input() min: number = 0;
  @Input() max: number = 100;
  @Input() step: number = 1;
  @Input() set value(val: number) {
    this.modelValue = [val];
  }
  get value(): number {
    return this.modelValue[0] || 0;
  }
  @Input() disabled: boolean = false;
  @Input() class?: string;
  @Output() valueChange = new EventEmitter<number>();

  modelValue: number[] = [50];

  get sliderClasses(): string {
    return cn(
      'relative flex w-full touch-none select-none items-center',
      this.class
    );
  }

  onValueChange(values: number[]): void {
    if (values && values.length > 0) {
      this.modelValue = values;
      this.valueChange.emit(values[0]);
    }
  }
}
