// packages/react/src/blocks/sidebar/Sidebar.tsx
import React, { useState } from 'react';
import { Button } from '@/components/ui/button/Button';
import { Separator } from '@/components/ui/separator/Separator';
import { SidebarItem } from './SidebarItem';
import { cn } from '@/lib/utils';
import type { SidebarProps, MenuItem } from './types';

export const Sidebar: React.FC<SidebarProps> = ({
  items,
  collapsible = true,
  defaultCollapsed = false,
  width = '280px',
  collapsedWidth = '60px',
  onItemClick,
  onCollapseChange,
  className,
}) => {
  const [isCollapsed, setIsCollapsed] = useState(defaultCollapsed);

  const toggleCollapse = () => {
    const newCollapsed = !isCollapsed;
    setIsCollapsed(newCollapsed);
    onCollapseChange?.(newCollapsed);
  };

  const handleItemClick = (item: MenuItem) => {
    onItemClick?.(item);
  };

  const currentWidth = isCollapsed ? collapsedWidth : width;

  return (
    <aside
      className={cn(
        'flex flex-col h-full border-r bg-card transition-all duration-300',
        className
      )}
      style={{ width: currentWidth }}
    >
      {/* Header */}
      <div className="flex items-center justify-between p-4">
        {!isCollapsed && (
          <div className="flex items-center gap-2">
            <div className="h-8 w-8 rounded bg-primary" />
            <h2 className="text-lg font-semibold">Menu</h2>
          </div>
        )}
        {isCollapsed && (
          <div className="flex justify-center w-full">
            <div className="h-8 w-8 rounded bg-primary" />
          </div>
        )}
      </div>

      <Separator />

      {/* Navigation Items */}
      <nav className="flex-1 overflow-y-auto p-2">
        {items.map((item) => (
          <SidebarItem
            key={item.id}
            item={item}
            collapsed={isCollapsed}
            onClick={handleItemClick}
          />
        ))}
      </nav>

      <Separator />

      {/* Footer */}
      <div className="p-2">
        {collapsible && (
          <Button
            variant="ghost"
            className={cn('w-full', isCollapsed && 'justify-center px-2')}
            onClick={toggleCollapse}
          >
            <svg
              xmlns="http://www.w3.org/2000/svg"
              width="16"
              height="16"
              viewBox="0 0 24 24"
              fill="none"
              stroke="currentColor"
              strokeWidth="2"
              strokeLinecap="round"
              strokeLinejoin="round"
              className={cn(
                'transition-transform',
                isCollapsed && 'rotate-180'
              )}
            >
              <path d="m15 18-6-6 6-6" />
            </svg>
            {!isCollapsed && <span className="ml-2">Collapse</span>}
          </Button>
        )}
      </div>
    </aside>
  );
};

// packages/vue/src/blocks/sidebar/Sidebar.vue
<script setup lang="ts">
import { ref, computed, type HTMLAttributes } from 'vue'
import Button from '@/components/ui/button/Button.vue'
import Separator from '@/components/ui/separator/separator.vue'
import SidebarItem from './SidebarItem.vue'
import { cn } from '@/lib/utils'
import type { SidebarProps, MenuItem } from './types'

interface Props extends SidebarProps {
  class?: HTMLAttributes['class']
}

const props = withDefaults(defineProps<Props>(), {
  collapsible: true,
  defaultCollapsed: false,
  width: '280px',
  collapsedWidth: '60px',
})

const emit = defineEmits<{
  itemClick: [item: MenuItem]
  collapseChange: [collapsed: boolean]
}>()

const isCollapsed = ref(props.defaultCollapsed)

const toggleCollapse = () => {
  isCollapsed.value = !isCollapsed.value
  emit('collapseChange', isCollapsed.value)
}

const currentWidth = computed(() => {
  return isCollapsed.value ? props.collapsedWidth : props.width
})

const handleItemClick = (item: MenuItem) => {
  emit('itemClick', item)
}
</script>

<template>
  <aside
    :class="cn(
      'flex flex-col h-full border-r bg-card transition-all duration-300',
      props.class
    )"
    :style="{ width: currentWidth }"
  >
    <!-- Header -->
    <div class="flex items-center justify-between p-4">
      <div v-if="!isCollapsed" class="flex items-center gap-2">
        <slot name="logo">
          <div class="h-8 w-8 rounded bg-primary" />
        </slot>
        <slot name="title">
          <h2 class="text-lg font-semibold">Menu</h2>
        </slot>
      </div>
      <div v-else class="flex justify-center w-full">
        <slot name="logo">
          <div class="h-8 w-8 rounded bg-primary" />
        </slot>
      </div>
    </div>

    <Separator />

    <!-- Navigation Items -->
    <nav class="flex-1 overflow-y-auto p-2">
      <SidebarItem
        v-for="item in items"
        :key="item.id"
        :item="item"
        :collapsed="isCollapsed"
        @click="handleItemClick"
      />
    </nav>

    <Separator />

    <!-- Footer -->
    <div class="p-2">
      <slot name="footer">
        <Button
          v-if="collapsible"
          variant="ghost"
          :class="cn(
            'w-full',
            isCollapsed && 'justify-center px-2'
          )"
          @click="toggleCollapse"
        >
          <svg
            xmlns="http://www.w3.org/2000/svg"
            width="16"
            height="16"
            viewBox="0 0 24 24"
            fill="none"
            stroke="currentColor"
            stroke-width="2"
            stroke-linecap="round"
            stroke-linejoin="round"
            :class="cn(
              'transition-transform',
              isCollapsed && 'rotate-180'
            )"
          >
            <path d="m15 18-6-6 6-6" />
          </svg>
          <span v-if="!isCollapsed" class="ml-2">Collapse</span>
        </Button>
      </slot>
    </div>
  </aside>
</template>
