// packages/vue/src/components/pagination/Pagination.vue
<!--
 * @author Bùi Trọng Hiếu
 * @email kevinbui210191@gmail.com
 * @desc Pagination component - Navigation with previous/next buttons and page numbers
-->
<script setup lang="ts">
import { cn } from '@/lib/utils'
import { computed } from 'vue'
import { ChevronLeft, ChevronRight, MoreHorizontal } from 'lucide-vue-next'

interface Props {
  /**
   * CSS class
   */
  class?: string
  /**
   * Current page number (1-indexed)
   */
  currentPage?: number
  /**
   * Total number of pages
   */
  totalPages?: number
  /**
   * Number of page buttons to show
   * @default 1
   */
  siblingCount?: number
}

const props = withDefaults(defineProps<Props>(), {
  currentPage: 1,
  totalPages: 1,
  siblingCount: 1,
})

const emit = defineEmits<{
  pageChange: [page: number]
}>()

const pages = computed(() => {
  const range = (start: number, end: number) => {
    return Array.from({ length: end - start + 1 }, (_, i) => start + i)
  }

  const totalPageNumbers = props.siblingCount + 5

  if (totalPageNumbers >= props.totalPages) {
    return range(1, props.totalPages)
  }

  const leftSiblingIndex = Math.max(props.currentPage - props.siblingCount, 1)
  const rightSiblingIndex = Math.min(
    props.currentPage + props.siblingCount,
    props.totalPages
  )

  const shouldShowLeftDots = leftSiblingIndex > 2
  const shouldShowRightDots = rightSiblingIndex < props.totalPages - 1

  if (!shouldShowLeftDots && shouldShowRightDots) {
    const leftItemCount = 3 + 2 * props.siblingCount
    const leftRange = range(1, leftItemCount)
    return [...leftRange, 'dots', props.totalPages]
  }

  if (shouldShowLeftDots && !shouldShowRightDots) {
    const rightItemCount = 3 + 2 * props.siblingCount
    const rightRange = range(props.totalPages - rightItemCount + 1, props.totalPages)
    return [1, 'dots', ...rightRange]
  }

  if (shouldShowLeftDots && shouldShowRightDots) {
    const middleRange = range(leftSiblingIndex, rightSiblingIndex)
    return [1, 'dots', ...middleRange, 'dots', props.totalPages]
  }

  return []
})

const handlePageChange = (page: number) => {
  if (page >= 1 && page <= props.totalPages && page !== props.currentPage) {
    emit('pageChange', page)
  }
}
</script>

<template>
  <nav
    role="navigation"
    aria-label="pagination"
    :class="cn('flex items-center justify-center', props.class)"
  >
    <ul class="flex items-center gap-1">
      <li>
        <button
          type="button"
          :class="
            cn(
              'inline-flex h-9 w-9 items-center justify-center rounded-md border border-input bg-background text-sm font-medium ring-offset-background transition-colors hover:bg-accent hover:text-accent-foreground focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:pointer-events-none disabled:opacity-50',
              currentPage === 1 && 'opacity-50 cursor-not-allowed'
            )
          "
          :disabled="currentPage === 1"
          @click="handlePageChange(currentPage - 1)"
          aria-label="Go to previous page"
        >
          <ChevronLeft class="h-4 w-4" />
        </button>
      </li>

      <li v-for="(page, index) in pages" :key="index">
        <span
          v-if="page === 'dots'"
          class="flex h-9 w-9 items-center justify-center text-sm"
        >
          <MoreHorizontal class="h-4 w-4" />
        </span>
        <button
          v-else
          type="button"
          :class="
            cn(
              'inline-flex h-9 min-w-[36px] items-center justify-center rounded-md border border-input bg-background px-3 text-sm font-medium ring-offset-background transition-colors hover:bg-accent hover:text-accent-foreground focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2',
              currentPage === page &&
                'border-primary bg-primary text-primary-foreground hover:bg-primary hover:text-primary-foreground'
            )
          "
          @click="handlePageChange(page as number)"
          :aria-label="`Go to page ${page}`"
          :aria-current="currentPage === page ? 'page' : undefined"
        >
          {{ page }}
        </button>
      </li>

      <li>
        <button
          type="button"
          :class="
            cn(
              'inline-flex h-9 w-9 items-center justify-center rounded-md border border-input bg-background text-sm font-medium ring-offset-background transition-colors hover:bg-accent hover:text-accent-foreground focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:pointer-events-none disabled:opacity-50',
              currentPage === totalPages && 'opacity-50 cursor-not-allowed'
            )
          "
          :disabled="currentPage === totalPages"
          @click="handlePageChange(currentPage + 1)"
          aria-label="Go to next page"
        >
          <ChevronRight class="h-4 w-4" />
        </button>
      </li>
    </ul>
  </nav>
</template>

// packages/react-native/src/components/pagination/Pagination.tsx
/**
 * @author Bùi Trọng Hiếu
 * @email kevinbui210191@gmail.com
 * @desc Pagination component for navigating through pages of data with multiple variants
 */

import * as React from 'react';
import { View, Text, Pressable, ActivityIndicator } from 'react-native';
import { cn } from '@/lib/utils';

export type PaginationVariant = 'compact' | 'full' | 'loadMore';

export interface PaginationProps {
  /** Current page number */
  currentPage: number;
  /** Total number of pages */
  totalPages: number;
  /** Called when the page changes */
  onPageChange?: (page: number) => void;
  /** Pagination variant (compact, full, loadMore) */
  variant?: PaginationVariant;
  /** Number of visible page buttons in compact mode */
  visiblePages?: number;
  /** Text for load more button */
  loadMoreText?: string;
  /** Loading state for load more variant */
  isLoading?: boolean;
  /** CSS class names for the container */
  className?: string;
}

export const Pagination = React.forwardRef<View, PaginationProps>(
  (
    {
      currentPage,
      totalPages,
      onPageChange,
      variant = 'compact',
      visiblePages = 5,
      loadMoreText = 'Load More',
      isLoading = false,
      className,
    },
    ref
  ) => {
    if (totalPages <= 1) {
      return null;
    }

    const renderContent = () => {
      switch (variant) {
        case 'compact':
          return (
            <CompactPagination
              currentPage={currentPage}
              totalPages={totalPages}
              onPageChange={onPageChange}
              visiblePages={visiblePages}
            />
          );
        case 'full':
          return (
            <FullPagination
              currentPage={currentPage}
              totalPages={totalPages}
              onPageChange={onPageChange}
            />
          );
        case 'loadMore':
          return (
            <LoadMorePagination
              currentPage={currentPage}
              totalPages={totalPages}
              onPageChange={onPageChange}
              loadMoreText={loadMoreText}
              isLoading={isLoading}
            />
          );
      }
    };

    return (
      <View ref={ref} className={cn('items-center py-4', className)}>
        {renderContent()}
      </View>
    );
  }
);

Pagination.displayName = 'Pagination';

// Compact Pagination Component
interface CompactPaginationProps {
  currentPage: number;
  totalPages: number;
  onPageChange?: (page: number) => void;
  visiblePages: number;
}

const CompactPagination: React.FC<CompactPaginationProps> = ({
  currentPage,
  totalPages,
  onPageChange,
  visiblePages,
}) => {
  const pages = getVisiblePages(currentPage, totalPages, visiblePages);

  return (
    <View className="flex-row items-center">
      {/* Previous button */}
      <IconButton
        icon="‹"
        onPress={() => onPageChange?.(currentPage - 1)}
        disabled={currentPage <= 1}
      />

      <View className="mx-2 flex-row">
        {pages.map((page, index) => {
          if (page === -1) {
            // Ellipsis
            return (
              <View key={`ellipsis-${index}`} className="px-2">
                <Text className="text-muted-foreground">...</Text>
              </View>
            );
          }

          const isSelected = page === currentPage;

          return (
            <PageButton
              key={page}
              page={page}
              isSelected={isSelected}
              onPress={() => onPageChange?.(page)}
            />
          );
        })}
      </View>

      {/* Next button */}
      <IconButton
        icon="›"
        onPress={() => onPageChange?.(currentPage + 1)}
        disabled={currentPage >= totalPages}
      />
    </View>
  );
};

// Full Pagination Component
interface FullPaginationProps {
  currentPage: number;
  totalPages: number;
  onPageChange?: (page: number) => void;
}

const FullPagination: React.FC<FullPaginationProps> = ({
  currentPage,
  totalPages,
  onPageChange,
}) => {
  return (
    <View className="flex-row items-center">
      {/* Previous button */}
      <IconButton
        icon="‹"
        onPress={() => onPageChange?.(currentPage - 1)}
        disabled={currentPage <= 1}
      />

      <View className="mx-2 flex-row flex-wrap justify-center">
        {Array.from({ length: totalPages }, (_, i) => i + 1).map((page) => {
          const isSelected = page === currentPage;

          return (
            <PageButton
              key={page}
              page={page}
              isSelected={isSelected}
              onPress={() => onPageChange?.(page)}
            />
          );
        })}
      </View>

      {/* Next button */}
      <IconButton
        icon="›"
        onPress={() => onPageChange?.(currentPage + 1)}
        disabled={currentPage >= totalPages}
      />
    </View>
  );
};

// Load More Pagination Component
interface LoadMorePaginationProps {
  currentPage: number;
  totalPages: number;
  onPageChange?: (page: number) => void;
  loadMoreText: string;
  isLoading: boolean;
}

const LoadMorePagination: React.FC<LoadMorePaginationProps> = ({
  currentPage,
  totalPages,
  onPageChange,
  loadMoreText,
  isLoading,
}) => {
  const hasMore = currentPage < totalPages;

  if (!hasMore) {
    return null;
  }

  return (
    <Pressable
      onPress={() => onPageChange?.(currentPage + 1)}
      disabled={isLoading}
      className={cn(
        'px-6 py-3 bg-primary rounded-lg',
        'active:opacity-80',
        isLoading && 'opacity-70'
      )}
    >
      {isLoading ? (
        <ActivityIndicator size="small" color="white" />
      ) : (
        <Text className="text-primary-foreground font-semibold">
          {loadMoreText}
        </Text>
      )}
    </Pressable>
  );
};

// Page Button Component
interface PageButtonProps {
  page: number;
  isSelected: boolean;
  onPress: () => void;
}

const PageButton: React.FC<PageButtonProps> = ({
  page,
  isSelected,
  onPress,
}) => {
  return (
    <Pressable
      onPress={onPress}
      className={cn(
        'w-10 h-10 items-center justify-center rounded-lg mx-1',
        'active:opacity-70',
        isSelected
          ? 'bg-primary'
          : 'border border-border'
      )}
    >
      <Text
        className={cn(
          'text-base',
          isSelected
            ? 'text-primary-foreground font-semibold'
            : 'text-foreground'
        )}
      >
        {page}
      </Text>
    </Pressable>
  );
};

// Icon Button Component
interface IconButtonProps {
  icon: string;
  onPress: () => void;
  disabled: boolean;
}

const IconButton: React.FC<IconButtonProps> = ({
  icon,
  onPress,
  disabled,
}) => {
  return (
    <Pressable
      onPress={onPress}
      disabled={disabled}
      className={cn(
        'w-10 h-10 items-center justify-center rounded-lg',
        'border border-border',
        'active:opacity-70',
        disabled && 'opacity-30'
      )}
    >
      <Text className="text-foreground text-xl">{icon}</Text>
    </Pressable>
  );
};

// Helper function to get visible pages
function getVisiblePages(
  currentPage: number,
  totalPages: number,
  visiblePages: number
): number[] {
  if (totalPages <= visiblePages) {
    return Array.from({ length: totalPages }, (_, i) => i + 1);
  }

  const half = Math.floor(visiblePages / 2);
  let start = currentPage - half;
  let end = currentPage + half;

  if (start < 1) {
    start = 1;
    end = visiblePages;
  }

  if (end > totalPages) {
    end = totalPages;
    start = totalPages - visiblePages + 1;
  }

  const pages: number[] = [];

  // Always show first page
  if (start > 1) {
    pages.push(1);
    if (start > 2) {
      pages.push(-1); // Ellipsis
    }
  }

  // Show visible range
  for (let i = start; i <= end; i++) {
    pages.push(i);
  }

  // Always show last page
  if (end < totalPages) {
    if (end < totalPages - 1) {
      pages.push(-1); // Ellipsis
    }
    pages.push(totalPages);
  }

  return pages;
}

// Static methods for creating variants
Pagination.compact = (props: Omit<PaginationProps, 'variant'>) => (
  <Pagination {...props} variant="compact" />
);

Pagination.full = (props: Omit<PaginationProps, 'variant'>) => (
  <Pagination {...props} variant="full" />
);

Pagination.loadMore = (
  props: Omit<PaginationProps, 'variant'> & {
    loadMoreText?: string;
    isLoading?: boolean;
  }
) => <Pagination {...props} variant="loadMore" />;

export { CompactPagination, FullPagination, LoadMorePagination };
