// packages/react/src/components/slider/Slider.tsx
/**
 * @author Bùi Trọng Hiếu
 * @email kevinbui210191@gmail.com
 * @desc Slider component - An input where the user selects a value from within a given range
 */

import * as React from 'react'
import * as SliderPrimitive from '@radix-ui/react-slider'
import { cn } from '@/lib/utils'

/**
 * Slider Props interface
 * @extends React.ComponentPropsWithoutRef<typeof SliderPrimitive.Root> - All standard slider root attributes
 */
export interface SliderProps extends React.ComponentPropsWithoutRef<typeof SliderPrimitive.Root> {
  /**
   * Controlled slider values
   */
  value?: number[]
  /**
   * Uncontrolled initial slider values
   */
  defaultValue?: number[]
  /**
   * Called when the slider values change
   */
  onValueChange?: (value: number[]) => void
  /**
   * Called when the interaction ends and the slider values are committed
   */
  onValueCommit?: (value: number[]) => void
  /**
   * Name used for the hidden inputs in form submission
   */
  name?: string
  /**
   * Disables the slider
   * @default false
   */
  disabled?: boolean
  /**
   * Slider orientation
   * @default 'horizontal'
   */
  orientation?: 'horizontal' | 'vertical'
  /**
   * Reading direction
   */
  dir?: 'ltr' | 'rtl'
  /**
   * Whether the slider is visually inverted
   * @default false
   */
  inverted?: boolean
  /**
   * Minimum value
   * @default 0
   */
  min?: number
  /**
   * Maximum value
   * @default 100
   */
  max?: number
  /**
   * Stepping interval
   * @default 1
   */
  step?: number
  /**
   * Minimum permitted steps between thumbs
   * @default 0
   */
  minStepsBetweenThumbs?: number
  /**
   * Associates the slider inputs with a form
   */
  form?: string
  /**
   * CSS class names for the slider root
   */
  className?: string
}

/**
 * Slider Component
 * 
 * An input where the user selects a value from within a given range.
 * Built on top of Radix UI Slider primitive.
 * 
 * @param {SliderProps} props - Slider component props
 * @param {string} [props.className] - CSS class names for the slider
 * @param {number[]} [props.value] - Current value(s) of the slider (controlled)
 * @param {number[]} [props.defaultValue] - Default value(s) of the slider (uncontrolled)
 * @param {number} [props.min=0] - Minimum value
 * @param {number} [props.max=100] - Maximum value
 * @param {number} [props.step=1] - Step interval
 * @param {boolean} [props.disabled=false] - Disables the slider
 * @param {'horizontal' | 'vertical'} [props.orientation='horizontal'] - Orientation of the slider
 * @param {(value: number[]) => void} [props.onValueChange] - Value change handler
 * @param {(value: number[]) => void} [props.onValueCommit] - Value commit handler
 * @param {React.RefObject<React.ElementRef<typeof SliderPrimitive.Root>>} ref - Reference to the slider element
 * @returns {JSX.Element} Slider element
 */
const Slider = React.forwardRef<
  React.ElementRef<typeof SliderPrimitive.Root>,
  SliderProps
>(({ className, ...props }, ref) => (
  <SliderPrimitive.Root
    ref={ref}
    className={cn(
      'relative flex w-full touch-none select-none items-center',
      className
    )}
    {...props}
  >
    <SliderPrimitive.Track className="relative h-2 w-full grow overflow-hidden rounded-full bg-secondary">
      <SliderPrimitive.Range className="absolute h-full bg-primary" />
    </SliderPrimitive.Track>
    <SliderPrimitive.Thumb className="block h-5 w-5 rounded-full border-2 border-primary bg-background ring-offset-background transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:pointer-events-none disabled:opacity-50" />
  </SliderPrimitive.Root>
))
Slider.displayName = SliderPrimitive.Root.displayName

export { Slider }

// packages/vue/src/components/slider/Slider.vue
<!--
 * @author Bùi Trọng Hiếu
 * @email kevinbui210191@gmail.com
 * @desc Slider component - Range slider input with min/max bounds and thumb control
-->
<script setup lang="ts">
import { type HTMLAttributes, computed } from 'vue'
import { SliderRange, SliderRoot, SliderThumb, SliderTrack, type SliderRootProps } from 'radix-vue'
import { cn } from '@/lib/utils'

/**
 * Slider Props
 * @prop modelValue - Controlled value
 * @prop defaultValue - Default value
 * @prop min - Minimum value
 * @prop max - Maximum value
 * @prop step - Step interval
 * @prop disabled - Disables the slider
 * @prop orientation - Slider orientation (horizontal or vertical)
 * @prop class - CSS class names for the slider
 */
interface Props extends SliderRootProps {
  /** Controlled value. */
  modelValue?: number[]
  /** Default value. */
  defaultValue?: number[]
  /** Minimum value. */
  min?: number
  /** Maximum value. */
  max?: number
  /** Step interval. */
  step?: number
  /** Disables the slider. */
  disabled?: boolean
  /** Slider orientation (horizontal or vertical). */
  orientation?: 'horizontal' | 'vertical'
  /** CSS class names for the slider. */
  class?: HTMLAttributes['class']
}

const props = defineProps<Props>()

const delegatedProps = computed(() => {
  const { class: _, ...delegated } = props
  return delegated
})
</script>

<template>
  <SliderRoot
    :class="cn('relative flex w-full touch-none select-none items-center', props.class)"
    v-bind="delegatedProps"
  >
    <SliderTrack class="relative h-2 w-full grow overflow-hidden rounded-full bg-secondary">
      <SliderRange class="absolute h-full bg-primary" />
    </SliderTrack>
    <SliderThumb
      class="block h-5 w-5 rounded-full border-2 border-primary bg-background ring-offset-background transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:pointer-events-none disabled:opacity-50"
    />
  </SliderRoot>
</template>
