// packages/angular/src/components/kbd/kbd.component.ts
/**
 * @author Bùi Trọng Hiếu
 * @email kevinbui210191@gmail.com
 * @desc Keyboard key display with 3 size variants
 */

import { Component, Input } from '@angular/core'
import { cn } from '@/lib/utils'

@Component({
  selector: 'ui-kbd',
  standalone: true,
  template: `
    <kbd [class]="className">
      <ng-content />
    </kbd>
  `,
})
export class KbdComponent {
  /**
   * CSS class
   */
  @Input() class?: string

  /**
   * Size variant
   * @default "default"
   */
  @Input() size: 'sm' | 'default' | 'lg' = 'default'

  get className(): string {
    return cn(
      'inline-flex items-center justify-center rounded border border-border bg-muted px-2 font-mono text-sm font-medium text-muted-foreground shadow-sm',
      {
        'h-5 min-w-[20px] text-xs': this.size === 'sm',
        'h-6 min-w-[24px] text-sm': this.size === 'default',
        'h-7 min-w-[28px] text-base': this.size === 'lg',
      },
      this.class
    )
  }
}

// packages/vue/src/components/kbd/Kbd.vue
<!--
 * @author Bùi Trọng Hiếu
 * @email kevinbui210191@gmail.com
 * @desc Kbd component - Keyboard key display with 3 size variants (sm, default, lg)
-->
<script setup lang="ts">
import { cn } from '@/lib/utils'
import { computed } from 'vue'

interface Props {
  /**
   * CSS class
   */
  class?: string
  /**
   * Size variant
   * @default "default"
   */
  size?: 'sm' | 'default' | 'lg'
}

const props = withDefaults(defineProps<Props>(), {
  size: 'default',
})

const className = computed(() =>
  cn(
    'inline-flex items-center justify-center rounded border border-border bg-muted px-2 font-mono text-sm font-medium text-muted-foreground shadow-sm',
    {
      'h-5 min-w-[20px] text-xs': props.size === 'sm',
      'h-6 min-w-[24px] text-sm': props.size === 'default',
      'h-7 min-w-[28px] text-base': props.size === 'lg',
    },
    props.class
  )
)
</script>

<template>
  <kbd :class="className">
    <slot />
  </kbd>
</template>
