// packages/vue/src/components/label/Label.vue
<!--
 * @author Bùi Trọng Hiếu
 * @email kevinbui210191@gmail.com
 * @desc Label component - Renders an accessible label associated with controls
-->
<script setup lang="ts">
import { type HTMLAttributes, computed } from 'vue'
import { Label as RadixLabel, type LabelProps as RadixLabelProps } from 'radix-vue'
import { cn } from '@/lib/utils'

/**
 * Label Props
 * @prop for - Id of the element the label is associated with
 * @prop asChild - Render as child via Radix Primitive
 * @prop as - Element or component to render
 * @prop class - CSS class names for the label
 */
interface LabelProps extends RadixLabelProps {
  /** Id of the element the label is associated with. */
  htmlFor?: string
  /** Render as child via Radix Primitive. */
  asChild?: boolean
  /** Element or component to render. */
  as?: string
  /** CSS class names for the label. */
  class?: HTMLAttributes['class']
}

const props = defineProps<LabelProps>()

const delegatedProps = computed(() => {
  const { class: _, ...delegated } = props
  return delegated
})
</script>

<template>
  <RadixLabel
    :class="cn(
      'text-sm font-medium leading-none peer-disabled:cursor-not-allowed peer-disabled:opacity-70',
      props.class
    )"
    v-bind="delegatedProps"
  >
    <slot />
  </RadixLabel>
</template>

// packages/angular/src/components/label/label.component.ts
/**
 * @author Bùi Trọng Hiếu
 * @email kevinbui210191@gmail.com
 * @desc Form label with accessible for attribute
 */

import { Component, Input, HostBinding, ChangeDetectionStrategy } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RdxLabelDirective } from '@radix-ng/primitives/label';
import { cn } from '@/lib/utils';

@Component({
  selector: 'ui-label, label[ui-label]',
  standalone: true,
  imports: [CommonModule],
  template: `<ng-content></ng-content>`,
  hostDirectives: [RdxLabelDirective],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class LabelComponent {
  @Input() htmlFor?: string;
  @Input() class?: string;

  @HostBinding('class')
  get hostClasses(): string {
    return cn(
      'text-sm font-medium leading-none peer-disabled:cursor-not-allowed peer-disabled:opacity-70',
      this.class
    );
  }

  @HostBinding('attr.for')
  get forAttribute(): string | null {
    return this.htmlFor || this.for || null;
  }
}
