// packages/angular/src/components/charts/line-chart.component.ts
/**
 * @author Bùi Trọng Hiếu
 * @email kevinbui210191@gmail.com
 * @desc Line Chart component - Responsive line chart powered by ECharts
 */

import {
  Component,
  Input,
  OnInit,
  OnChanges,
  SimpleChanges,
  ChangeDetectionStrategy,
} from '@angular/core'
import { CommonModule } from '@angular/common'
import { NgxEchartsModule, NgxEchartsDirective } from 'ngx-echarts'
import type { EChartsOption } from 'echarts'
import { cn } from '@/lib/utils'
import type { LineChartProps, ChartData } from './types'
import {
  buildEChartsOption,
  getResponsiveDimensions,
  transformDataToSeries,
} from './utils'

@Component({
  selector: 'ui-line-chart',
  standalone: true,
  imports: [CommonModule, NgxEchartsModule],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <div [class]="containerClass">
      <!-- Empty State -->
      <div
        *ngIf="!chartOption && !loading"
        class="flex items-center justify-center bg-gray-50 dark:bg-gray-900 rounded-lg border border-gray-200 dark:border-gray-700"
        [style.height]="dimensions.height"
      >
        <p class="text-gray-500 dark:text-gray-400">{{ emptyText }}</p>
      </div>

      <!-- Chart -->
      <div
        *ngIf="chartOption"
        echarts
        [options]="chartOption"
        [theme]="theme"
        [loading]="loading"
        [loadingOpts]="loadingOption"
        [style.height]="dimensions.height"
        [style.width]="dimensions.width"
        class="echarts-container"
      ></div>
    </div>
  `,
  styles: [
    `
      :host {
        display: block;
        width: 100%;
      }

      .echarts-container {
        position: relative;
      }

      /* Dark mode support */
      :host-context(.dark) {
        color-scheme: dark;
      }
    `,
  ],
})
export class LineChartComponent implements OnInit, OnChanges {
  @Input({ required: true }) data!: ChartData
  @Input() height: number = 300
  @Input() width?: number | string
  @Input() theme: 'light' | 'dark' = 'light'
  @Input() legend: boolean = true
  @Input() legendPosition: 'top' | 'bottom' | 'left' | 'right' = 'top'
  @Input() grid: boolean | Record<string, unknown> = true
  @Input() tooltip: boolean | Record<string, unknown> = true
  @Input() animation: boolean = true
  @Input() smooth: boolean = true
  @Input() showPoints: boolean = true
  @Input() pointSize: number = 6
  @Input() area: boolean = false
  @Input() stack: boolean = false
  @Input() zoom: boolean = false
  @Input() dataLabels: boolean = false
  @Input() loading: boolean = false
  @Input() emptyText: string = 'No data available'
  @Input() className?: string
  @Input() options: Record<string, unknown> = {}

  chartOption: EChartsOption | null = null
  dimensions: { width: string; height: string } = { width: '100%', height: '300px' }

  loadingOption = {
    text: 'Loading...',
    color: '#3b82f6',
    textColor: '#666',
    maskColor: 'rgba(255, 255, 255, 0.8)',
    zlevel: 0,
  }

  get containerClass(): string {
    return cn('galaxy-line-chart w-full', this.className)
  }

  ngOnInit(): void {
    this.updateChart()
  }

  ngOnChanges(changes: SimpleChanges): void {
    if (
      changes['data'] ||
      changes['height'] ||
      changes['width'] ||
      changes['theme'] ||
      changes['smooth'] ||
      changes['area'] ||
      changes['options']
    ) {
      this.updateChart()
    }
  }

  private updateChart(): void {
    // Update dimensions
    this.dimensions = getResponsiveDimensions(this.width, this.height)

    // Check for empty data
    if (!this.data || !this.data.datasets || this.data.datasets.length === 0) {
      this.chartOption = null
      return
    }

    // Build base option
    const baseOption = buildEChartsOption({
      data: this.data,
      height: this.height,
      width: this.width,
      theme: this.theme,
      legend: this.legend,
      legendPosition: this.legendPosition,
      grid: this.grid,
      tooltip: this.tooltip,
      animation: this.animation,
      zoom: this.zoom,
      options: this.options,
      chartType: 'line',
    })

    // Apply line-specific configurations
    const series = transformDataToSeries(this.data, 'line', {
      smooth: this.smooth,
      showSymbol: this.showPoints,
      symbolSize: this.pointSize,
      stack: this.stack ? 'total' : undefined,
      areaStyle: this.area
        ? {
            opacity: 0.3,
          }
        : undefined,
      label: this.dataLabels
        ? {
            show: true,
            position: 'top',
          }
        : undefined,
    })

    this.chartOption = {
      ...baseOption,
      series,
    }
  }
}

// packages/vue/src/components/charts/LineChart.vue
<!--
 * @author Bùi Trọng Hiếu
 * @email kevinbui210191@gmail.com
 * @desc LineChart component - Line chart with smooth curve and area fill support powered by ECharts
-->
<script setup lang="ts">
import { computed } from 'vue'
import VChart from 'vue-echarts'
import { use } from 'echarts/core'
import { LineChart } from 'echarts/charts'
import {
  GridComponent,
  TooltipComponent,
  LegendComponent,
  DataZoomComponent,
} from 'echarts/components'
import { CanvasRenderer } from 'echarts/renderers'
import { cn } from '@/lib/utils'
import type { LineChartProps } from './types'
import {
  buildEChartsOption,
  getResponsiveDimensions,
  transformDataToSeries,
} from './utils'

// Register ECharts components
use([
  LineChart,
  GridComponent,
  TooltipComponent,
  LegendComponent,
  DataZoomComponent,
  CanvasRenderer,
])

interface Props extends LineChartProps {
  class?: string
}

const props = withDefaults(defineProps<Props>(), {
  height: 300,
  theme: 'light',
  legend: true,
  legendPosition: 'top',
  grid: true,
  tooltip: true,
  animation: true,
  smooth: true,
  showPoints: true,
  pointSize: 6,
  area: false,
  stack: false,
  zoom: false,
  dataLabels: false,
  loading: false,
  emptyText: 'No data available',
})

// Build ECharts option
const chartOption = computed(() => {
  // Check for empty data
  if (!props.data || !props.data.datasets || props.data.datasets.length === 0) {
    return null
  }

  const baseOption = buildEChartsOption({
    ...props,
    chartType: 'line',
  })

  // Apply line-specific configurations
  const series = transformDataToSeries(props.data, 'line', {
    smooth: props.smooth,
    showSymbol: props.showPoints,
    symbolSize: props.pointSize,
    stack: props.stack ? 'total' : undefined,
    areaStyle: props.area
      ? {
          opacity: 0.3,
        }
      : undefined,
    label: props.dataLabels
      ? {
          show: true,
          position: 'top',
        }
      : undefined,
  })

  return {
    ...baseOption,
    series,
  }
})

// Get responsive dimensions
const dimensions = computed(() => getResponsiveDimensions(props.width, props.height))

// Loading option for ECharts
const loadingOption = computed(() => ({
  text: 'Loading...',
  color: '#3b82f6',
  textColor: '#666',
  maskColor: 'rgba(255, 255, 255, 0.8)',
  zlevel: 0,
}))
</script>

<template>
  <div :class="cn('galaxy-line-chart w-full', props.class)">
    <!-- Empty State -->
    <div
      v-if="!chartOption && !loading"
      class="flex items-center justify-center bg-gray-50 dark:bg-gray-900 rounded-lg border border-gray-200 dark:border-gray-700"
      :style="{ height: dimensions.height }"
    >
      <p class="text-gray-500 dark:text-gray-400">{{ emptyText }}</p>
    </div>

    <!-- Chart -->
    <VChart
      v-else-if="chartOption"
      :option="chartOption"
      :style="dimensions"
      :theme="theme"
      :loading="loading"
      :loading-options="loadingOption"
      autoresize
    />
  </div>
</template>

<style scoped>
.galaxy-line-chart {
  position: relative;
}

/* Dark mode support */
:deep(.dark) .galaxy-line-chart {
  color-scheme: dark;
}
</style>
