// packages/vue/src/components/navigation-menu/NavigationMenu.vue
<!--
 * @author Bùi Trọng Hiếu
 * @email kevinbui210191@gmail.com
 * @desc NavigationMenu component - Horizontal navigation with dropdown support
-->
<script setup lang="ts">
import { type HTMLAttributes, computed } from 'vue'
import { NavigationMenuRoot, type NavigationMenuRootProps } from 'radix-vue'
import { cn } from '@/lib/utils'

/**
 * NavigationMenu Props
 * @prop modelValue - Controlled value of the active menu item
 * @prop defaultValue - Initial active item for uncontrolled usage
 * @prop dir - Reading direction (ltr, rtl)
 * @prop orientation - Layout orientation (horizontal, vertical)
 * @prop delayDuration - Delay before content opens
 * @prop skipDelayDuration - Skip delay for keyboard users
 * @prop disableMenuItemTrigger - Disable menu item trigger
 * @prop class - CSS class names for the navigation menu
 */
interface Props extends NavigationMenuRootProps {
  /** Controlled value of the active menu item. */
  modelValue?: string
  /** Initial active item for uncontrolled usage. */
  defaultValue?: string
  /** Reading direction (ltr, rtl). */
  dir?: 'ltr' | 'rtl'
  /** Layout orientation (horizontal, vertical). */
  orientation?: 'horizontal' | 'vertical'
  /** Delay before content opens. */
  delayDuration?: number
  /** Skip delay for keyboard users. */
  skipDelayDuration?: number
  /** Disable menu item trigger. */
  disableMenuItemTrigger?: boolean
  /** CSS class names for the navigation menu. */
  class?: HTMLAttributes['class']
}

const props = defineProps<Props>()
const delegatedProps = computed(() => {
  const { class: _, ...delegated } = props
  return delegated
})
</script>

<template>
  <NavigationMenuRoot
    :class="cn('relative z-10 flex max-w-max flex-1 items-center justify-center', props.class)"
    v-bind="delegatedProps"
  >
    <slot />
  </NavigationMenuRoot>
</template>

// packages/react/src/components/navigation-menu/NavigationMenu.tsx
/**
 * @author Bùi Trọng Hiếu
 * @email kevinbui210191@gmail.com
 * @desc Navigation Menu components - A collection of menus for navigating pages and links
 */

import * as React from 'react'
import * as NavigationMenuPrimitive from '@radix-ui/react-navigation-menu'
import { cn } from '@/lib/utils'

/**
 * NavigationMenu Props interface
 * @extends React.ComponentPropsWithoutRef<typeof NavigationMenuPrimitive.Root> - All standard navigation menu root attributes
 */
export type NavigationMenuProps = React.ComponentPropsWithoutRef<
  typeof NavigationMenuPrimitive.Root
> & {
  /**
   * Current active menu item value
   */
  value?: string
  /**
   * Uncontrolled initial active menu item value
   */
  defaultValue?: string
  /**
   * Called when the active item changes
   */
  onValueChange?: (value: string) => void
  /**
   * Delay duration before content closes
   */
  delayDuration?: number
  /**
   * Skip delay duration
   */
  skipDelayDuration?: number
  /**
   * Reading direction
   * @default 'ltr'
   */
  dir?: 'ltr' | 'rtl'
  /**
   * CSS class names for the navigation menu
   */
  className?: string
}

/**
 * NavigationMenu Component
 * 
 * Root component for the navigation menu. Manages the menu state and positioning.
 * Built on top of Radix UI NavigationMenu primitive.
 * 
 * @param {NavigationMenuProps} props - NavigationMenu component props
 * @param {string} [props.className] - CSS class names for the navigation menu
 * @param {string} [props.value] - Current active menu item value
 * @param {string} [props.defaultValue] - Uncontrolled initial active menu item value
 * @param {(value: string) => void} [props.onValueChange] - Active item change handler
 * @param {number} [props.delayDuration] - Delay before content closes
 * @param {number} [props.skipDelayDuration] - Skip delay duration
 * @param {'ltr' | 'rtl'} [props.dir='ltr'] - Reading direction
 * @param {React.RefObject<React.ElementRef<typeof NavigationMenuPrimitive.Root>>} ref - Reference to the menu element
 * @returns {JSX.Element} Navigation menu container element
 */
const NavigationMenu = React.forwardRef<
  React.ElementRef<typeof NavigationMenuPrimitive.Root>,
  NavigationMenuProps
>(({ className, ...props }, ref) => (
  <NavigationMenuPrimitive.Root
    ref={ref}
    className={cn('relative z-10 flex max-w-max flex-1 items-center justify-center', className)}
    {...props}
  />
))
NavigationMenu.displayName = NavigationMenuPrimitive.Root.displayName

/**
 * NavigationMenuList Component
 * 
 * A container for navigation menu items. Renders as a horizontal list.
 */
const NavigationMenuList = NavigationMenuPrimitive.List

/**
 * NavigationMenuItem Component
 * 
 * An individual item within the navigation menu.
 */
const NavigationMenuItem = NavigationMenuPrimitive.Item

/**
 * NavigationMenuTrigger Component
 * 
 * The trigger element that opens a navigation menu submenu.
 */
const NavigationMenuTrigger = NavigationMenuPrimitive.Trigger

/**
 * NavigationMenuContent Component
 * 
 * The content panel for a navigation menu item. Displays when triggered.
 */
const NavigationMenuContent = NavigationMenuPrimitive.Content

/**
 * NavigationMenuLink Component
 * 
 * A link within the navigation menu. Supports both internal and external links.
 */
const NavigationMenuLink = NavigationMenuPrimitive.Link

export { NavigationMenu }
export {
  NavigationMenuList,
  NavigationMenuItem,
  NavigationMenuTrigger,
  NavigationMenuContent,
  NavigationMenuLink,
}
