// examples/angular-admin-dashboard/src/app/layouts/dashboard-layout.ts
import { Component } from '@angular/core';
import { RouterOutlet, Router } from '@angular/router';
import { SidebarComponent, SidebarItemComponent } from '@/components/ui/sidebar';
import { ButtonComponent } from '@/components/ui/button';

interface MenuItem {
  id: string;
  label: string;
  icon?: string;
  href?: string;
}

@Component({
  selector: 'app-dashboard-layout',
  standalone: true,
  imports: [RouterOutlet, SidebarComponent, SidebarItemComponent, ButtonComponent],
  template: `
    <div class="min-h-screen flex bg-gray-50">
      <ui-sidebar
        [items]="menuItems"
        (itemClick)="handleItemClick($event)"
        (collapseChange)="handleCollapseChange($event)"
      />
      <div class="flex-1 flex flex-col">
        <header class="bg-white border-b p-4 flex justify-between items-center">
          <h1 class="text-xl font-bold">Galaxy UI Admin Dashboard (Angular)</h1>
        </header>
        <main class="flex-1 p-8 overflow-auto">
          <router-outlet />
        </main>
      </div>
    </div>
  `,
  styles: [],
})
export class DashboardLayoutComponent {
  menuItems: MenuItem[] = [
    { id: 'dashboard', label: 'Dashboard', href: '/dashboard' },
    { id: 'forms', label: 'Form Components', href: '/dashboard/forms' },
    { id: 'data', label: 'Data Display', href: '/dashboard/data' },
    { id: 'feedback', label: 'Feedback', href: '/dashboard/feedback' },
    { id: 'navigation', label: 'Navigation', href: '/dashboard/navigation' },
    { id: 'layout', label: 'Layout', href: '/dashboard/layout' },
  ];

  constructor(private router: Router) {}

  handleItemClick(item: MenuItem) {
    if (item.href) {
      this.router.navigate([item.href]);
    }
  }

  handleCollapseChange(collapsed: boolean) {
    // Handle collapse state if needed
  }
}

// examples/react-admin-dashboard/src/layouts/DashboardLayout.tsx
import { Outlet, useNavigate } from 'react-router-dom'
import { useAuth } from '../contexts/AuthContext'
import { Sidebar } from '@/components/ui/sidebar'
import { Button } from '@/components/ui/button'
import type { MenuItem } from '@/components/ui/sidebar/types'
import { LayoutDashboard, FileText, Database, MessageSquare, Compass, Layout } from 'lucide-react'

export function DashboardLayout() {
  const { logout } = useAuth()
  const navigate = useNavigate()

  const handleLogout = () => {
    logout()
    navigate('/login')
  }

  const menuItems: MenuItem[] = [
    { id: 'dashboard', label: 'Dashboard', icon: <LayoutDashboard className="w-5 h-5" />, href: '/dashboard' },
    { id: 'forms', label: 'Form Components', icon: <FileText className="w-5 h-5" />, href: '/dashboard/forms' },
    { id: 'data', label: 'Data Display', icon: <Database className="w-5 h-5" />, href: '/dashboard/data' },
    { id: 'feedback', label: 'Feedback', icon: <MessageSquare className="w-5 h-5" />, href: '/dashboard/feedback' },
    { id: 'navigation', label: 'Navigation', icon: <Compass className="w-5 h-5" />, href: '/dashboard/navigation' },
    { id: 'layout', label: 'Layout', icon: <Layout className="w-5 h-5" />, href: '/dashboard/layout' },
  ]

  const handleItemClick = (item: MenuItem) => {
    if (item.href) {
      navigate(item.href)
    }
  }

  return (
    <div className="min-h-screen flex bg-gray-50">
      <Sidebar
        items={menuItems}
        onItemClick={handleItemClick}
        onCollapseChange={() => {}}
      />
      <div className="flex-1 flex flex-col">
        <header className="bg-white border-b p-4 flex justify-between items-center">
          <h1 className="text-xl font-bold">Galaxy UI Admin Dashboard</h1>
          <Button variant="outline" onClick={handleLogout}>
            Logout
          </Button>
        </header>
        <main className="flex-1 p-8 overflow-auto">
          <Outlet />
        </main>
      </div>
    </div>
  )
}
